<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Education inequality | DATA 3320 Data Science Methodology and Applications</title>
  <meta name="description" content="The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Education inequality | DATA 3320 Data Science Methodology and Applications" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="The output format for this example is bookdown::gitbook." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Education inequality | DATA 3320 Data Science Methodology and Applications" />
  
  <meta name="twitter:description" content="The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Brian Fischer" />


<meta name="date" content="2021-02-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Overview</a></li>
<li class="chapter" data-level="2" data-path="edgap.html"><a href="edgap.html"><i class="fa fa-check"></i><b>2</b> Education inequality</a><ul>
<li class="chapter" data-level="2.1" data-path="edgap.html"><a href="edgap.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="edgap.html"><a href="edgap.html#data-collection"><i class="fa fa-check"></i><b>2.2</b> Data Collection</a><ul>
<li class="chapter" data-level="2.2.1" data-path="edgap.html"><a href="edgap.html#edgap-data"><i class="fa fa-check"></i><b>2.2.1</b> EdGap data</a></li>
<li class="chapter" data-level="2.2.2" data-path="edgap.html"><a href="edgap.html#school-information-data"><i class="fa fa-check"></i><b>2.2.2</b> School information data</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="edgap.html"><a href="edgap.html#data-preparation"><i class="fa fa-check"></i><b>2.3</b> Data Preparation</a><ul>
<li class="chapter" data-level="2.3.1" data-path="edgap.html"><a href="edgap.html#load-necessary-libraries"><i class="fa fa-check"></i><b>2.3.1</b> Load necessary libraries</a></li>
<li class="chapter" data-level="2.3.2" data-path="edgap.html"><a href="edgap.html#load-the-data"><i class="fa fa-check"></i><b>2.3.2</b> Load the data</a></li>
<li class="chapter" data-level="2.3.3" data-path="edgap.html"><a href="edgap.html#explore-the-contents-of-the-data-set"><i class="fa fa-check"></i><b>2.3.3</b> Explore the contents of the data set</a></li>
<li class="chapter" data-level="2.3.4" data-path="edgap.html"><a href="edgap.html#check-for-a-tidy-data-frame"><i class="fa fa-check"></i><b>2.3.4</b> Check for a tidy data frame</a></li>
<li class="chapter" data-level="2.3.5" data-path="edgap.html"><a href="edgap.html#further-exploration-of-basic-properties"><i class="fa fa-check"></i><b>2.3.5</b> Further exploration of basic properties</a></li>
<li class="chapter" data-level="2.3.6" data-path="edgap.html"><a href="edgap.html#data-cleaning"><i class="fa fa-check"></i><b>2.3.6</b> Data cleaning</a></li>
<li class="chapter" data-level="2.3.7" data-path="edgap.html"><a href="edgap.html#are-there-data-points-that-look-like-errors"><i class="fa fa-check"></i><b>2.3.7</b> Are there data points that look like errors?</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="edgap.html"><a href="edgap.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>2.4</b> Exploratory data analysis</a><ul>
<li class="chapter" data-level="2.4.1" data-path="edgap.html"><a href="edgap.html#graphical-summaries"><i class="fa fa-check"></i><b>2.4.1</b> Graphical summaries</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="edgap.html"><a href="edgap.html#model"><i class="fa fa-check"></i><b>2.5</b> Model</a><ul>
<li class="chapter" data-level="2.5.1" data-path="edgap.html"><a href="edgap.html#simple-linear-regression-with-each-socioeconomic-predictor"><i class="fa fa-check"></i><b>2.5.1</b> Simple linear regression with each socioeconomic predictor</a></li>
<li class="chapter" data-level="2.5.2" data-path="edgap.html"><a href="edgap.html#model-selection"><i class="fa fa-check"></i><b>2.5.2</b> Model selection</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="edgap.html"><a href="edgap.html#additional-step"><i class="fa fa-check"></i><b>2.6</b> Additional step</a></li>
<li class="chapter" data-level="2.7" data-path="edgap.html"><a href="edgap.html#conclusion"><i class="fa fa-check"></i><b>2.7</b> Conclusion</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">DATA 3320 Data Science Methodology and Applications</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="edgap" class="section level1">
<h1><span class="header-section-number">Chapter 2</span> Education inequality</h1>
<div id="introduction" class="section level2">
<h2><span class="header-section-number">2.1</span> Introduction</h2>
<p>This project addresses education inequality in U.S. high schools. The quality of a high school education can be measured in multiple ways, but here we will focus on average student performance on the ACT or SAT exams that students take as part of the college application process.</p>
<p>We expect a range of school performance on these exams, but is school performance predicted by socioeconomic factors?</p>
</div>
<div id="data-collection" class="section level2">
<h2><span class="header-section-number">2.2</span> Data Collection</h2>
<p>This project utilizes two data sets. The primary data set is the EdGap data set from <a href="https://www.edgap.org/#5/37.875/-96.987">EdGap.org</a>. This data set from 2016 includes information about average ACT or SAT scores for schools and several socioeconomic characteristics of the school district. The secondary data set is basic information about each school from the <a href="https://nces.ed.gov/ccd/pubschuniv.asp">National Center for Education Statistics</a>.</p>
<div id="edgap-data" class="section level3">
<h3><span class="header-section-number">2.2.1</span> EdGap data</h3>
<p>All socioeconomic data (household income, unemployment, adult educational attainment, and family structure) is from the Census Bureau’s American Community Survey.</p>
<p><a href="https://www.edgap.org/#5/37.875/-96.987">EdGap.org</a> report that ACT and SAT score data is from each state’s department of education or some other public data release. The nature of the other public data release is not known.</p>
<p>The quality of the census data and the department of education data can be assumed to be reasonably high.</p>
<p><a href="https://www.edgap.org/#5/37.875/-96.987">EdGap.org</a> do not indicate that they processed the data in any way. The data were assembled by the <a href="https://www.edgap.org/#5/37.875/-96.987">EdGap.org</a> team, so there is always the possibility for human error. Given the public nature of the data, we would be able to consult the original data sources to check the quality of the data if we had any questions.</p>
</div>
<div id="school-information-data" class="section level3">
<h3><span class="header-section-number">2.2.2</span> School information data</h3>
<p>The school information data is from the <a href="https://nces.ed.gov/ccd/pubschuniv.asp">National Center for Education Statistics</a>. This data set consists of basic identifying information about schools can be assumed to be reasonably high. As for the EdGap.org data, the school information data is public, so we would be able to consult the original data sources to check the quality of the data if we had any questions.</p>
</div>
</div>
<div id="data-preparation" class="section level2">
<h2><span class="header-section-number">2.3</span> Data Preparation</h2>
<div id="load-necessary-libraries" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Load necessary libraries</h3>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="edgap.html#cb1-1"></a><span class="co">#tidyverse contains packages we will use for processing and plotting data</span></span>
<span id="cb1-2"><a href="edgap.html#cb1-2"></a><span class="kw">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.3     ✓ purrr   0.3.4
## ✓ tibble  3.0.4     ✓ dplyr   1.0.2
## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
## ✓ readr   1.4.0     ✓ forcats 0.5.0</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="edgap.html#cb5-1"></a><span class="co">#readxl lets us read Excel files</span></span>
<span id="cb5-2"><a href="edgap.html#cb5-2"></a><span class="kw">library</span>(readxl)</span>
<span id="cb5-3"><a href="edgap.html#cb5-3"></a><span class="co">#GGally has a nice pairs plotting function</span></span>
<span id="cb5-4"><a href="edgap.html#cb5-4"></a><span class="kw">library</span>(GGally)</span></code></pre></div>
<pre><code>## Registered S3 method overwritten by &#39;GGally&#39;:
##   method from   
##   +.gg   ggplot2</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="edgap.html#cb7-1"></a><span class="co">#skimr provides a nice summary of a data set</span></span>
<span id="cb7-2"><a href="edgap.html#cb7-2"></a><span class="kw">library</span>(skimr)</span>
<span id="cb7-3"><a href="edgap.html#cb7-3"></a><span class="co">#leaps will be used for model selection</span></span>
<span id="cb7-4"><a href="edgap.html#cb7-4"></a><span class="kw">library</span>(leaps)</span>
<span id="cb7-5"><a href="edgap.html#cb7-5"></a><span class="co">#kableExtra will be used to make tables in the html document</span></span>
<span id="cb7-6"><a href="edgap.html#cb7-6"></a><span class="kw">library</span>(kableExtra)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;kableExtra&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     group_rows</code></pre>
</div>
<div id="load-the-data" class="section level3">
<h3><span class="header-section-number">2.3.2</span> Load the data</h3>
<div id="load-the-edgap-set" class="section level4">
<h4><span class="header-section-number">2.3.2.1</span> Load the EdGap set</h4>
<p><span class="math inline">\(\rightarrow\)</span> Load the data set contained in the file <code>Data for SAT ACT correlation with census tract data.xlsx</code> and name the data frame <code>edgap</code>.</p>
<details>
<p><summary><strong>Show Coding Hint</strong></summary></p>
<p>Use the function <code>read_excel</code> from the package <code>readxl</code> to load the data.</p>
</details>
<p><br></p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="edgap.html#cb10-1"></a>edgap &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;EdGap_data.xlsx&quot;</span>)</span></code></pre></div>
</details>
<p><br></p>
</div>
</div>
<div id="explore-the-contents-of-the-data-set" class="section level3">
<h3><span class="header-section-number">2.3.3</span> Explore the contents of the data set</h3>
<p><span class="math inline">\(\rightarrow\)</span> Look at the first few rows of the data frame.</p>
<details>
<p><summary><strong>Show Coding Hint</strong></summary></p>
<p>You can use the function <code>head</code> to see the head of the data frame.</p>
</details>
<p><br></p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="edgap.html#cb11-1"></a><span class="kw">head</span>(edgap, <span class="dt">n =</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 7
##   `NCESSCH School… `CT Unemploymen… `CT Pct Adults … `CT Pct Childre…
##              &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;
## 1     100001600143           0.118             0.445            0.346
## 2     100008000024           0.0640            0.663            0.768
## 3     100008000225           0.0565            0.702            0.713
## 4     100017000029           0.0447            0.692            0.641
## 5     100018000040           0.0770            0.640            0.834
## # … with 3 more variables: `CT Median Household Income` &lt;dbl&gt;, `School ACT
## #   average (or equivalent if SAT score)` &lt;dbl&gt;, `School Pct Free and Reduced
## #   Lunch` &lt;dbl&gt;</code></pre>
We used the option <code>n = 5</code> to show the first 5 rows.
</details>
<p><br></p>
<p>Use the <code>View</code> function to explore the full data set.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="edgap.html#cb13-1"></a><span class="kw">View</span>(edgap)</span></code></pre></div>
<div id="load-school-information-data" class="section level4">
<h4><span class="header-section-number">2.3.3.1</span> Load school information data</h4>
<p><span class="math inline">\(\rightarrow\)</span> Load the data set contained in the file <code>ccd_sch_029_1617_w_1a_11212017.csv</code> and name the data frame <code>school_info</code>.</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="edgap.html#cb14-1"></a>school_info &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;ccd_sch_029_1617_w_1a_11212017.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   .default = col_character(),
##   UNION = col_logical(),
##   MSTREET2 = col_logical(),
##   MSTREET3 = col_logical(),
##   MZIP = col_double(),
##   MZIP4 = col_logical(),
##   LSTREET2 = col_logical(),
##   LSTREET3 = col_logical(),
##   LZIP = col_double(),
##   LZIP4 = col_logical(),
##   SY_STATUS = col_double(),
##   UPDATED_STATUS = col_double(),
##   SCH_TYPE = col_double(),
##   CHARTAUTH1 = col_logical(),
##   CHARTAUTHN1 = col_logical(),
##   CHARTAUTH2 = col_logical(),
##   CHARTAUTHN2 = col_logical()
## )
## ℹ Use `spec()` for the full column specifications.</code></pre>
<pre><code>## Warning: 138139 parsing failures.
##  row   col           expected actual                                 file
## 1549 MZIP4 1/0/T/F/TRUE/FALSE   8999 &#39;ccd_sch_029_1617_w_1a_11212017.csv&#39;
## 1550 MZIP4 1/0/T/F/TRUE/FALSE   0800 &#39;ccd_sch_029_1617_w_1a_11212017.csv&#39;
## 1551 MZIP4 1/0/T/F/TRUE/FALSE   0700 &#39;ccd_sch_029_1617_w_1a_11212017.csv&#39;
## 1552 MZIP4 1/0/T/F/TRUE/FALSE   0050 &#39;ccd_sch_029_1617_w_1a_11212017.csv&#39;
## 1553 MZIP4 1/0/T/F/TRUE/FALSE   0019 &#39;ccd_sch_029_1617_w_1a_11212017.csv&#39;
## .... ..... .................. ...... ....................................
## See problems(...) for more details.</code></pre>
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Look at the first few rows of the data frame.</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="edgap.html#cb17-1"></a><span class="kw">head</span>(school_info)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 65
##   SCHOOL_YEAR FIPST STATENAME ST    SCH_NAME LEA_NAME STATE_AGENCY_NO UNION
##   &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;           &lt;lgl&gt;
## 1 2016-2017   01    ALABAMA   AL    Sequoya… Alabama… 01              NA   
## 2 2016-2017   01    ALABAMA   AL    Camps    Alabama… 01              NA   
## 3 2016-2017   01    ALABAMA   AL    Det Ctr  Alabama… 01              NA   
## 4 2016-2017   01    ALABAMA   AL    Wallace… Alabama… 01              NA   
## 5 2016-2017   01    ALABAMA   AL    McNeel … Alabama… 01              NA   
## 6 2016-2017   01    ALABAMA   AL    Alabama… Alabama… 01              NA   
## # … with 57 more variables: ST_LEAID &lt;chr&gt;, LEAID &lt;chr&gt;, ST_SCHID &lt;chr&gt;,
## #   NCESSCH &lt;chr&gt;, SCHID &lt;chr&gt;, MSTREET1 &lt;chr&gt;, MSTREET2 &lt;lgl&gt;, MSTREET3 &lt;lgl&gt;,
## #   MCITY &lt;chr&gt;, MSTATE &lt;chr&gt;, MZIP &lt;dbl&gt;, MZIP4 &lt;lgl&gt;, LSTREET1 &lt;chr&gt;,
## #   LSTREET2 &lt;lgl&gt;, LSTREET3 &lt;lgl&gt;, LCITY &lt;chr&gt;, LSTATE &lt;chr&gt;, LZIP &lt;dbl&gt;,
## #   LZIP4 &lt;lgl&gt;, PHONE &lt;chr&gt;, WEBSITE &lt;chr&gt;, SY_STATUS &lt;dbl&gt;,
## #   SY_STATUS_TEXT &lt;chr&gt;, UPDATED_STATUS &lt;dbl&gt;, UPDATED_STATUS_TEXT &lt;chr&gt;,
## #   EFFECTIVE_DATE &lt;chr&gt;, SCH_TYPE_TEXT &lt;chr&gt;, SCH_TYPE &lt;dbl&gt;,
## #   RECON_STATUS &lt;chr&gt;, OUT_OF_STATE_FLAG &lt;chr&gt;, CHARTER_TEXT &lt;chr&gt;,
## #   CHARTAUTH1 &lt;lgl&gt;, CHARTAUTHN1 &lt;lgl&gt;, CHARTAUTH2 &lt;lgl&gt;, CHARTAUTHN2 &lt;lgl&gt;,
## #   NOGRADES &lt;chr&gt;, G_PK_OFFERED &lt;chr&gt;, G_KG_OFFERED &lt;chr&gt;, G_1_OFFERED &lt;chr&gt;,
## #   G_2_OFFERED &lt;chr&gt;, G_3_OFFERED &lt;chr&gt;, G_4_OFFERED &lt;chr&gt;, G_5_OFFERED &lt;chr&gt;,
## #   G_6_OFFERED &lt;chr&gt;, G_7_OFFERED &lt;chr&gt;, G_8_OFFERED &lt;chr&gt;, G_9_OFFERED &lt;chr&gt;,
## #   G_10_OFFERED &lt;chr&gt;, G_11_OFFERED &lt;chr&gt;, G_12_OFFERED &lt;chr&gt;,
## #   G_13_OFFERED &lt;chr&gt;, G_UG_OFFERED &lt;chr&gt;, G_AE_OFFERED &lt;chr&gt;, GSLO &lt;chr&gt;,
## #   GSHI &lt;chr&gt;, LEVEL &lt;chr&gt;, IGOFFERED &lt;chr&gt;</code></pre>
</details>
<p><br></p>
</div>
</div>
<div id="check-for-a-tidy-data-frame" class="section level3">
<h3><span class="header-section-number">2.3.4</span> Check for a tidy data frame</h3>
<p>In a tidy data set, each column is a variable or id and each row is an observation. We again start by looking at the head of the data frame to determine if the data frame is tidy.</p>
<div id="edgap-data-1" class="section level4">
<h4><span class="header-section-number">2.3.4.1</span> EdGap data</h4>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="edgap.html#cb19-1"></a><span class="kw">head</span>(edgap)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 7
##   `NCESSCH School… `CT Unemploymen… `CT Pct Adults … `CT Pct Childre…
##              &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;
## 1     100001600143           0.118             0.445            0.346
## 2     100008000024           0.0640            0.663            0.768
## 3     100008000225           0.0565            0.702            0.713
## 4     100017000029           0.0447            0.692            0.641
## 5     100018000040           0.0770            0.640            0.834
## 6     100019000050           0.0801            0.673            0.483
## # … with 3 more variables: `CT Median Household Income` &lt;dbl&gt;, `School ACT
## #   average (or equivalent if SAT score)` &lt;dbl&gt;, `School Pct Free and Reduced
## #   Lunch` &lt;dbl&gt;</code></pre>
<p>The units of observation are the schools. Each school occupies one row of the data frame, which is what we want for the rows.</p>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> What variables are present? What types of variables are present?</p>
<details>
<p><summary><strong>Show Coding Hint</strong></summary></p>
<p>There are several ways to get this information:</p>
<ol style="list-style-type: decimal">
<li><p>The <code>head</code> of the data frame shows the names of the variables and how they are represented.</p></li>
<li><p>The function <code>skim</code> from the library <code>skimr</code> produces a summary of the data that includes a</p></li>
<li><p>The functions <code>glimpse</code> and <code>str</code> produce a summary of the data frame that is similar to the <code>head</code>.</p></li>
</ol>
<p>You should explore multiple approaches as you learn what each function can do, but you do not need to use all of the approaches each time you explore a data set.</p>
</details>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="edgap.html#cb21-1"></a><span class="kw">skim</span>(edgap)</span></code></pre></div>
<table style='width: auto;'
        class='table table-condensed'>
<caption>
<span id="tab:unnamed-chunk-9">Table 2.1: </span>Data summary
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
edgap
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
7986
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
7
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
7
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
NCESSCH School ID
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3.321869e+11
</td>
<td style="text-align:right;">
1.323638e+11
</td>
<td style="text-align:right;">
1.000016e+11
</td>
<td style="text-align:right;">
2.105340e+11
</td>
<td style="text-align:right;">
3.600085e+11
</td>
<td style="text-align:right;">
4.226678e+11
</td>
<td style="text-align:right;">
5.60583e+11
</td>
<td style="text-align:left;">
▇▆▆▅▇
</td>
</tr>
<tr>
<td style="text-align:left;">
CT Unemployment Rate
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.000000e-01
</td>
<td style="text-align:right;">
6.000000e-02
</td>
<td style="text-align:right;">
0.000000e+00
</td>
<td style="text-align:right;">
6.000000e-02
</td>
<td style="text-align:right;">
9.000000e-02
</td>
<td style="text-align:right;">
1.200000e-01
</td>
<td style="text-align:right;">
5.90000e-01
</td>
<td style="text-align:left;">
▇▃▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
CT Pct Adults with College Degree
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5.700000e-01
</td>
<td style="text-align:right;">
1.700000e-01
</td>
<td style="text-align:right;">
9.000000e-02
</td>
<td style="text-align:right;">
4.500000e-01
</td>
<td style="text-align:right;">
5.500000e-01
</td>
<td style="text-align:right;">
6.800000e-01
</td>
<td style="text-align:right;">
1.00000e+00
</td>
<td style="text-align:left;">
▁▅▇▅▂
</td>
</tr>
<tr>
<td style="text-align:left;">
CT Pct Childre In Married Couple Family
</td>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
6.300000e-01
</td>
<td style="text-align:right;">
2.000000e-01
</td>
<td style="text-align:right;">
0.000000e+00
</td>
<td style="text-align:right;">
5.200000e-01
</td>
<td style="text-align:right;">
6.700000e-01
</td>
<td style="text-align:right;">
7.800000e-01
</td>
<td style="text-align:right;">
1.00000e+00
</td>
<td style="text-align:left;">
▁▂▅▇▃
</td>
</tr>
<tr>
<td style="text-align:left;">
CT Median Household Income
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5.202691e+04
</td>
<td style="text-align:right;">
2.422806e+04
</td>
<td style="text-align:right;">
3.589000e+03
</td>
<td style="text-align:right;">
3.659725e+04
</td>
<td style="text-align:right;">
4.683350e+04
</td>
<td style="text-align:right;">
6.136925e+04
</td>
<td style="text-align:right;">
2.26181e+05
</td>
<td style="text-align:left;">
▇▆▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
School ACT average (or equivalent if SAT score)
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2.018000e+01
</td>
<td style="text-align:right;">
2.600000e+00
</td>
<td style="text-align:right;">
-3.070000e+00
</td>
<td style="text-align:right;">
1.860000e+01
</td>
<td style="text-align:right;">
2.040000e+01
</td>
<td style="text-align:right;">
2.191000e+01
</td>
<td style="text-align:right;">
3.23600e+01
</td>
<td style="text-align:left;">
▁▁▂▇▁
</td>
</tr>
<tr>
<td style="text-align:left;">
School Pct Free and Reduced Lunch
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4.200000e-01
</td>
<td style="text-align:right;">
2.400000e-01
</td>
<td style="text-align:right;">
-5.000000e-02
</td>
<td style="text-align:right;">
2.400000e-01
</td>
<td style="text-align:right;">
3.800000e-01
</td>
<td style="text-align:right;">
5.800000e-01
</td>
<td style="text-align:right;">
1.00000e+00
</td>
<td style="text-align:left;">
▃▇▆▃▂
</td>
</tr>
</tbody>
</table>
<p>We have 7 columns, but the first column is a school ID, not a variable measured for the school. It is also important to note that each column is a unique variable; we do not have values for one variable that are separated over multiple columns. So, there are 6 variables present.</p>
<p>Each column contains numeric values. We should be careful to note that this does not mean that each column is a numerical variable. For example, <code>NCESSCH School ID</code> is an identifier, so even though it is coded as a numeric value, it is a categorical variable. We may make transformations of such variables to factors to help with analyses.</p>
<p>Here we provide a more readable description of each variable.</p>
<p><strong>Data dictionary</strong></p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
name
</th>
<th style="text-align:left;">
description
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
NCESSCH School ID
</td>
<td style="text-align:left;">
NCES school ID
</td>
</tr>
<tr>
<td style="text-align:left;">
CT Unemployment Rate
</td>
<td style="text-align:left;">
unemployment rate
</td>
</tr>
<tr>
<td style="text-align:left;">
CT Pct Adults with College Degree
</td>
<td style="text-align:left;">
percent of adults with a college degree
</td>
</tr>
<tr>
<td style="text-align:left;">
CT Pct Childre In Married Couple Family
</td>
<td style="text-align:left;">
percent of children in a married couple family
</td>
</tr>
<tr>
<td style="text-align:left;">
CT Median Household Income
</td>
<td style="text-align:left;">
median household income
</td>
</tr>
<tr>
<td style="text-align:left;">
School ACT average (or equivalent if SAT score)
</td>
<td style="text-align:left;">
average school ACT or equivalent if SAT score
</td>
</tr>
<tr>
<td style="text-align:left;">
School Pct Free and Reduced Lunch
</td>
<td style="text-align:left;">
percent of students at the school who receive free or reduced price lunch
</td>
</tr>
</tbody>
</table>
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Is the <code>edgap</code> data frame tidy?</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<p>Yes, each column is a variable or id and each row is an observation, so the data frame is tidy.</p>
</details>
</div>
<div id="school-information-data-1" class="section level4">
<h4><span class="header-section-number">2.3.4.2</span> School information data</h4>
<p>We again start by looking at the head of the data frame to determine if the data frame is tidy.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="edgap.html#cb22-1"></a><span class="kw">head</span>(school_info)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 65
##   SCHOOL_YEAR FIPST STATENAME ST    SCH_NAME LEA_NAME STATE_AGENCY_NO UNION
##   &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;           &lt;lgl&gt;
## 1 2016-2017   01    ALABAMA   AL    Sequoya… Alabama… 01              NA   
## 2 2016-2017   01    ALABAMA   AL    Camps    Alabama… 01              NA   
## 3 2016-2017   01    ALABAMA   AL    Det Ctr  Alabama… 01              NA   
## 4 2016-2017   01    ALABAMA   AL    Wallace… Alabama… 01              NA   
## 5 2016-2017   01    ALABAMA   AL    McNeel … Alabama… 01              NA   
## 6 2016-2017   01    ALABAMA   AL    Alabama… Alabama… 01              NA   
## # … with 57 more variables: ST_LEAID &lt;chr&gt;, LEAID &lt;chr&gt;, ST_SCHID &lt;chr&gt;,
## #   NCESSCH &lt;chr&gt;, SCHID &lt;chr&gt;, MSTREET1 &lt;chr&gt;, MSTREET2 &lt;lgl&gt;, MSTREET3 &lt;lgl&gt;,
## #   MCITY &lt;chr&gt;, MSTATE &lt;chr&gt;, MZIP &lt;dbl&gt;, MZIP4 &lt;lgl&gt;, LSTREET1 &lt;chr&gt;,
## #   LSTREET2 &lt;lgl&gt;, LSTREET3 &lt;lgl&gt;, LCITY &lt;chr&gt;, LSTATE &lt;chr&gt;, LZIP &lt;dbl&gt;,
## #   LZIP4 &lt;lgl&gt;, PHONE &lt;chr&gt;, WEBSITE &lt;chr&gt;, SY_STATUS &lt;dbl&gt;,
## #   SY_STATUS_TEXT &lt;chr&gt;, UPDATED_STATUS &lt;dbl&gt;, UPDATED_STATUS_TEXT &lt;chr&gt;,
## #   EFFECTIVE_DATE &lt;chr&gt;, SCH_TYPE_TEXT &lt;chr&gt;, SCH_TYPE &lt;dbl&gt;,
## #   RECON_STATUS &lt;chr&gt;, OUT_OF_STATE_FLAG &lt;chr&gt;, CHARTER_TEXT &lt;chr&gt;,
## #   CHARTAUTH1 &lt;lgl&gt;, CHARTAUTHN1 &lt;lgl&gt;, CHARTAUTH2 &lt;lgl&gt;, CHARTAUTHN2 &lt;lgl&gt;,
## #   NOGRADES &lt;chr&gt;, G_PK_OFFERED &lt;chr&gt;, G_KG_OFFERED &lt;chr&gt;, G_1_OFFERED &lt;chr&gt;,
## #   G_2_OFFERED &lt;chr&gt;, G_3_OFFERED &lt;chr&gt;, G_4_OFFERED &lt;chr&gt;, G_5_OFFERED &lt;chr&gt;,
## #   G_6_OFFERED &lt;chr&gt;, G_7_OFFERED &lt;chr&gt;, G_8_OFFERED &lt;chr&gt;, G_9_OFFERED &lt;chr&gt;,
## #   G_10_OFFERED &lt;chr&gt;, G_11_OFFERED &lt;chr&gt;, G_12_OFFERED &lt;chr&gt;,
## #   G_13_OFFERED &lt;chr&gt;, G_UG_OFFERED &lt;chr&gt;, G_AE_OFFERED &lt;chr&gt;, GSLO &lt;chr&gt;,
## #   GSHI &lt;chr&gt;, LEVEL &lt;chr&gt;, IGOFFERED &lt;chr&gt;</code></pre>
<p>It is more difficult to assess whether this data frame is tidy because of the large number of columns with confusing names.</p>
<p>We have 65 columns, but many of the columns are identifying features of the school and are irrelevant for the analysis. We will select a subset of columns and do the analysis on the subset.</p>
</div>
<div id="select-a-subset-of-columns" class="section level4">
<h4><span class="header-section-number">2.3.4.3</span> Select a subset of columns</h4>
<p>We want to select the following variables:</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
name
</th>
<th style="text-align:left;">
description
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
NCESSCH
</td>
<td style="text-align:left;">
NCES School ID
</td>
</tr>
<tr>
<td style="text-align:left;">
MSTATE
</td>
<td style="text-align:left;">
State name
</td>
</tr>
<tr>
<td style="text-align:left;">
MZIP
</td>
<td style="text-align:left;">
Zip code
</td>
</tr>
<tr>
<td style="text-align:left;">
SCH_TYPE_TEXT
</td>
<td style="text-align:left;">
School type
</td>
</tr>
<tr>
<td style="text-align:left;">
LEVEL
</td>
<td style="text-align:left;">
LEVEL
</td>
</tr>
</tbody>
</table>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Use the <code>select</code> function to select these columns from the data frame.</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="edgap.html#cb24-1"></a><span class="co">#We redefine the data frame to be the smaller version</span></span>
<span id="cb24-2"><a href="edgap.html#cb24-2"></a>school_info &lt;-<span class="st"> </span>school_info <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb24-3"><a href="edgap.html#cb24-3"></a><span class="st">  </span><span class="kw">select</span>(NCESSCH,MSTATE,MZIP,SCH_TYPE_TEXT,LEVEL)</span></code></pre></div>
</details>
<p><span class="math inline">\(\rightarrow\)</span> Examine the head of the new, smaller data frame</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="edgap.html#cb25-1"></a><span class="kw">head</span>(school_info)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##   NCESSCH      MSTATE  MZIP SCH_TYPE_TEXT      LEVEL         
##   &lt;chr&gt;        &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;              &lt;chr&gt;         
## 1 010000200277 AL     35220 Alternative School High          
## 2 010000201667 AL     36057 Alternative School High          
## 3 010000201670 AL     36057 Alternative School High          
## 4 010000201705 AL     36057 Alternative School High          
## 5 010000201706 AL     35206 Alternative School High          
## 6 010000201876 AL     35080 Regular School     Not applicable</code></pre>
</details>
<p><span class="math inline">\(\rightarrow\)</span> Is the data frame tidy?</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<p>Yes, each column is a variable or id and each row is an observation, so the data frame is tidy.</p>
</details>
</div>
</div>
<div id="further-exploration-of-basic-properties" class="section level3">
<h3><span class="header-section-number">2.3.5</span> Further exploration of basic properties</h3>
<div id="edgap-data-2" class="section level4">
<h4><span class="header-section-number">2.3.5.1</span> EdGap data</h4>
<p><span class="math inline">\(\rightarrow\)</span> How many observations are in the EdGap data set?</p>
<details>
<p><summary><strong>Show Algorithmic Hint</strong></summary></p>
<p>The number of observations is equal to the number of rows in the data frame.</p>
</details>
<details>
<p><summary><strong>Show Coding Hint</strong></summary></p>
<p>The number of rows in a data frame is one of the outputs of the <code>skim</code> function.</p>
<p>The number of rows in a data frame can be found using the function <code>nrows</code>.</p>
<p>You can also use the function <code>dim</code> to get the number of rows and columns in a data frame.</p>
</details>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="edgap.html#cb27-1"></a><span class="kw">nrow</span>(edgap)</span></code></pre></div>
<pre><code>## [1] 7986</code></pre>
There are 7986 rows, so there are 7986 observations in the data set.
</details>
</div>
<div id="school-information-data-2" class="section level4">
<h4><span class="header-section-number">2.3.5.2</span> School information data</h4>
<p><span class="math inline">\(\rightarrow\)</span> How many observations are in the school information data set?</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="edgap.html#cb29-1"></a><span class="kw">nrow</span>(school_info)</span></code></pre></div>
<pre><code>## [1] 102181</code></pre>
There are 102,181 rows, so there are 102,181 observations in the data set. The EdGap data clearly is a subset of all schools.
</details>
</div>
</div>
<div id="data-cleaning" class="section level3">
<h3><span class="header-section-number">2.3.6</span> Data cleaning</h3>
<div id="rename-variables" class="section level4">
<h4><span class="header-section-number">2.3.6.1</span> Rename variables</h4>
<p>In any analysis, we might rename the variables in the data frame to make them easier to work with. We have seen that the variable names in the <code>edgap</code> data frame allow us to understand them, but they can be improved. In contrast, many of the variables in the <code>school_info</code> data frame have confusing names.</p>
<p>Importantly, we should be thinking ahead to joining the two data frames based on the school ID. To facilitate this join, we should give the school ID column the same name in each data frame.</p>
</div>
<div id="edgap-data-3" class="section level4">
<h4><span class="header-section-number">2.3.6.2</span> EdGap data</h4>
<span class="math inline">\(\rightarrow\)</span> View the column names for the EdGap data
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="edgap.html#cb31-1"></a><span class="kw">names</span>(edgap)</span></code></pre></div>
<pre><code>## [1] &quot;NCESSCH School ID&quot;                              
## [2] &quot;CT Unemployment Rate&quot;                           
## [3] &quot;CT Pct Adults with College Degree&quot;              
## [4] &quot;CT Pct Childre In Married Couple Family&quot;        
## [5] &quot;CT Median Household Income&quot;                     
## [6] &quot;School ACT average (or equivalent if SAT score)&quot;
## [7] &quot;School Pct Free and Reduced Lunch&quot;</code></pre>
</details>
<p><br></p>
<p>To follow best practices, we should</p>
<ol style="list-style-type: decimal">
<li>Use all lowercase letters in variable names.</li>
<li>Use underscores <code>_</code> between words in a variable name. Do not use blank spaces, as they have done.</li>
<li>Do not use abbreviations, e.g. <code>Pct</code>, that can easily be written out.</li>
<li>Be consistent with naming structure across variables. For example, the descriptions <code>rate</code>, <code>percent</code>, <code>median</code>, and <code>average</code> should all either be at the beginning or end of the name.</li>
</ol>
<p>We will use the <code>rename</code> function from the <code>dplyr</code> package to rename the columns.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="edgap.html#cb33-1"></a><span class="co">#The new name for the column is on the left of the =</span></span>
<span id="cb33-2"><a href="edgap.html#cb33-2"></a></span>
<span id="cb33-3"><a href="edgap.html#cb33-3"></a>edgap &lt;-<span class="st"> </span>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb33-4"><a href="edgap.html#cb33-4"></a><span class="st">  </span><span class="kw">rename</span>(<span class="dt">id =</span> <span class="st">&quot;NCESSCH School ID&quot;</span>,</span>
<span id="cb33-5"><a href="edgap.html#cb33-5"></a>         <span class="dt">rate_unemployment =</span> <span class="st">&quot;CT Unemployment Rate&quot;</span>,</span>
<span id="cb33-6"><a href="edgap.html#cb33-6"></a>         <span class="dt">percent_college =</span> <span class="st">&quot;CT Pct Adults with College Degree&quot;</span>,</span>
<span id="cb33-7"><a href="edgap.html#cb33-7"></a>         <span class="dt">percent_married =</span> <span class="st">&quot;CT Pct Childre In Married Couple Family&quot;</span>,</span>
<span id="cb33-8"><a href="edgap.html#cb33-8"></a>         <span class="dt">median_income =</span> <span class="st">&quot;CT Median Household Income&quot;</span>,</span>
<span id="cb33-9"><a href="edgap.html#cb33-9"></a>         <span class="dt">average_act =</span> <span class="st">&quot;School ACT average (or equivalent if SAT score)&quot;</span>,</span>
<span id="cb33-10"><a href="edgap.html#cb33-10"></a>         <span class="dt">percent_lunch =</span> <span class="st">&quot;School Pct Free and Reduced Lunch&quot;</span></span>
<span id="cb33-11"><a href="edgap.html#cb33-11"></a>        )</span></code></pre></div>
<p><span class="math inline">\(\rightarrow\)</span> Use the <code>names</code> function to see that the names have changed</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="edgap.html#cb34-1"></a><span class="kw">names</span>(edgap)</span></code></pre></div>
<pre><code>## [1] &quot;id&quot;                &quot;rate_unemployment&quot; &quot;percent_college&quot;  
## [4] &quot;percent_married&quot;   &quot;median_income&quot;     &quot;average_act&quot;      
## [7] &quot;percent_lunch&quot;</code></pre>
</details>
</div>
<div id="school-information-data-3" class="section level4">
<h4><span class="header-section-number">2.3.6.3</span> School information data</h4>
<p><span class="math inline">\(\rightarrow\)</span> View the column names for the school information data</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="edgap.html#cb36-1"></a><span class="kw">names</span>(school_info)</span></code></pre></div>
<pre><code>## [1] &quot;NCESSCH&quot;       &quot;MSTATE&quot;        &quot;MZIP&quot;          &quot;SCH_TYPE_TEXT&quot;
## [5] &quot;LEVEL&quot;</code></pre>
</details>
<p><br></p>
<p>The names can be improved for readability. We also have the constraint that we rename <code>ncessch</code> to <code>id</code> to be consistent with the <code>edgap</code> data.</p>
<p>Rename the columns of the school information data frame.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="edgap.html#cb38-1"></a>school_info &lt;-<span class="st"> </span>school_info <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb38-2"><a href="edgap.html#cb38-2"></a><span class="st">  </span><span class="kw">rename</span>(<span class="dt">id =</span> <span class="st">&quot;NCESSCH&quot;</span>,</span>
<span id="cb38-3"><a href="edgap.html#cb38-3"></a>         <span class="dt">state =</span> <span class="st">&quot;MSTATE&quot;</span>,</span>
<span id="cb38-4"><a href="edgap.html#cb38-4"></a>         <span class="dt">zip_code =</span> <span class="st">&quot;MZIP&quot;</span>,</span>
<span id="cb38-5"><a href="edgap.html#cb38-5"></a>         <span class="dt">school_type =</span> <span class="st">&quot;SCH_TYPE_TEXT&quot;</span>,</span>
<span id="cb38-6"><a href="edgap.html#cb38-6"></a>         <span class="dt">school_level =</span> <span class="st">&quot;LEVEL&quot;</span></span>
<span id="cb38-7"><a href="edgap.html#cb38-7"></a>         )</span>
<span id="cb38-8"><a href="edgap.html#cb38-8"></a></span>
<span id="cb38-9"><a href="edgap.html#cb38-9"></a><span class="co">#Print the names to see the change</span></span>
<span id="cb38-10"><a href="edgap.html#cb38-10"></a><span class="kw">names</span>(school_info)</span></code></pre></div>
<pre><code>## [1] &quot;id&quot;           &quot;state&quot;        &quot;zip_code&quot;     &quot;school_type&quot;  &quot;school_level&quot;</code></pre>
</div>
<div id="join" class="section level4">
<h4><span class="header-section-number">2.3.6.4</span> Join</h4>
<p>We will join the <code>edgap</code> and <code>school_info</code> data frames based on the school ID. We should first note that the <code>id</code> is coded differently in the two data frames:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="edgap.html#cb40-1"></a><span class="kw">typeof</span>(edgap<span class="op">$</span>id)</span></code></pre></div>
<pre><code>## [1] &quot;double&quot;</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="edgap.html#cb42-1"></a><span class="kw">typeof</span>(school_info<span class="op">$</span>id)</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>While <code>id</code> is a number, it is a categorical variable and should be represented as a character variable in R.</p>
<p>Convert <code>id</code> in <code>edgap</code> id to a character variable:</p>
<p>We will use the <code>mutate</code> function from the <code>dplyr</code> package to rename the columns.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="edgap.html#cb44-1"></a>edgap &lt;-<span class="st"> </span>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb44-2"><a href="edgap.html#cb44-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">id =</span> <span class="kw">as.character</span>(id))</span>
<span id="cb44-3"><a href="edgap.html#cb44-3"></a></span>
<span id="cb44-4"><a href="edgap.html#cb44-4"></a><span class="co">#Check that the type has been converted to character</span></span>
<span id="cb44-5"><a href="edgap.html#cb44-5"></a><span class="kw">typeof</span>(edgap<span class="op">$</span>id)</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>We will now join the data frames. We want to perform a left join based on the school ID <code>id</code> so that we incorporate all of the school information into the <code>edgap</code> data frame.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="edgap.html#cb46-1"></a>edgap &lt;-<span class="st"> </span>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb46-2"><a href="edgap.html#cb46-2"></a><span class="st">  </span><span class="kw">left_join</span>(school_info, <span class="dt">by =</span> <span class="st">&quot;id&quot;</span>) </span></code></pre></div>
<p>Examine the head of the new data frame:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="edgap.html#cb47-1"></a><span class="kw">head</span>(edgap)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 11
##   id    rate_unemployme… percent_college percent_married median_income
##   &lt;chr&gt;            &lt;dbl&gt;           &lt;dbl&gt;           &lt;dbl&gt;         &lt;dbl&gt;
## 1 1000…           0.118            0.445           0.346         42820
## 2 1000…           0.0640           0.663           0.768         89320
## 3 1000…           0.0565           0.702           0.713         84140
## 4 1000…           0.0447           0.692           0.641         56500
## 5 1000…           0.0770           0.640           0.834         54015
## 6 1000…           0.0801           0.673           0.483         50649
## # … with 6 more variables: average_act &lt;dbl&gt;, percent_lunch &lt;dbl&gt;, state &lt;chr&gt;,
## #   zip_code &lt;dbl&gt;, school_type &lt;chr&gt;, school_level &lt;chr&gt;</code></pre>
</div>
<div id="identify-and-deal-with-missing-values" class="section level4">
<h4><span class="header-section-number">2.3.6.5</span> Identify and deal with missing values</h4>
<p><span class="math inline">\(\rightarrow\)</span> How many missing values are there in each column? Give the number of missing values and the percent of values in each column that are missing.</p>
<p>Recall that missing values are coded in R with <code>NA</code>, or they may be empty. We want to convert empty cells to <code>NA</code>, so that we can use the function <code>is.na</code> to find all missing values. The function <code>read_excel</code> that we used to read in the data does this automatically, so we do not need to take further action to deal with empty cells.</p>
<details>
<p><summary><strong>Show Coding Hint</strong></summary></p>
<p>This is easiest using the <code>skim</code> function. This function count the number of <code>NA</code>s in each column, gives the percentage of complete results, and provides the 5-number summary, mean, and standard deviation of each column.</p>
<p>The function <code>is.na</code> produces a set of logical TRUE and FALSE values the same dimension as the data that indicates whether a value is NA or not.</p>
<p>The functions <code>map_df</code> and <code>sum</code>, or the function <code>colSums</code> can be used together with <code>is.na</code> to count the number of <code>NA</code>s in each column.</p>
</details>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<p>Solution using <code>map_df</code></p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="edgap.html#cb49-1"></a>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb49-2"><a href="edgap.html#cb49-2"></a><span class="st">  </span><span class="kw">map_df</span>(<span class="op">~</span><span class="kw">sum</span>(<span class="kw">is.na</span>(.)))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 11
##      id rate_unemployme… percent_college percent_married median_income
##   &lt;int&gt;            &lt;int&gt;           &lt;int&gt;           &lt;int&gt;         &lt;int&gt;
## 1     0               14              13              25            20
## # … with 6 more variables: average_act &lt;int&gt;, percent_lunch &lt;int&gt;, state &lt;int&gt;,
## #   zip_code &lt;int&gt;, school_type &lt;int&gt;, school_level &lt;int&gt;</code></pre>
<p>Show the results as a percent of the number of observations:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="edgap.html#cb51-1"></a>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb51-2"><a href="edgap.html#cb51-2"></a><span class="st">  </span><span class="kw">map_df</span>(<span class="op">~</span><span class="kw">sum</span>(<span class="kw">is.na</span>(.)))<span class="op">/</span><span class="kw">nrow</span>(edgap)<span class="op">*</span><span class="dv">100</span> </span></code></pre></div>
<pre><code>##   id rate_unemployment percent_college percent_married median_income
## 1  0         0.1753068       0.1627849       0.3130478     0.2504383
##   average_act percent_lunch    state zip_code school_type school_level
## 1           0             0 1.101928 1.101928    1.101928     1.101928</code></pre>
<p>Solution using <code>colSums</code></p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="edgap.html#cb53-1"></a><span class="co">#Using pipes </span></span>
<span id="cb53-2"><a href="edgap.html#cb53-2"></a>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb53-3"><a href="edgap.html#cb53-3"></a><span class="st">  </span><span class="kw">is.na</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb53-4"><a href="edgap.html#cb53-4"></a><span class="st">  </span><span class="kw">colSums</span>()</span></code></pre></div>
<pre><code>##                id rate_unemployment   percent_college   percent_married 
##                 0                14                13                25 
##     median_income       average_act     percent_lunch             state 
##                20                 0                 0                88 
##          zip_code       school_type      school_level 
##                88                88                88</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="edgap.html#cb55-1"></a><span class="co">#alternatively without using the pipe operator:</span></span>
<span id="cb55-2"><a href="edgap.html#cb55-2"></a><span class="co">#colSums(is.na(edgap))</span></span></code></pre></div>
<p>Show the results as a percent of the number of observations:</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="edgap.html#cb56-1"></a>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb56-2"><a href="edgap.html#cb56-2"></a><span class="st">  </span><span class="kw">is.na</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb56-3"><a href="edgap.html#cb56-3"></a><span class="st">  </span><span class="kw">colSums</span>()<span class="op">/</span><span class="kw">nrow</span>(edgap)<span class="op">*</span><span class="dv">100</span> </span></code></pre></div>
<pre><code>##                id rate_unemployment   percent_college   percent_married 
##         0.0000000         0.1753068         0.1627849         0.3130478 
##     median_income       average_act     percent_lunch             state 
##         0.2504383         0.0000000         0.0000000         1.1019284 
##          zip_code       school_type      school_level 
##         1.1019284         1.1019284         1.1019284</code></pre>
<p>Solution using <code>skim</code></p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="edgap.html#cb58-1"></a><span class="kw">skim</span>(edgap)</span></code></pre></div>
<table style='width: auto;'
        class='table table-condensed'>
<caption>
<span id="tab:unnamed-chunk-30">Table 2.2: </span>Data summary
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
edgap
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
7986
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
11
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
7
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
empty
</th>
<th style="text-align:right;">
n_unique
</th>
<th style="text-align:right;">
whitespace
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
id
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
7986
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
state
</td>
<td style="text-align:right;">
88
</td>
<td style="text-align:right;">
0.99
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
school_type
</td>
<td style="text-align:right;">
88
</td>
<td style="text-align:right;">
0.99
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
school_level
</td>
<td style="text-align:right;">
88
</td>
<td style="text-align:right;">
0.99
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
rate_unemployment
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
0.10
</td>
<td style="text-align:right;">
0.06
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.06
</td>
<td style="text-align:right;">
0.09
</td>
<td style="text-align:right;">
0.12
</td>
<td style="text-align:right;">
0.59
</td>
<td style="text-align:left;">
▇▃▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
percent_college
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
0.57
</td>
<td style="text-align:right;">
0.17
</td>
<td style="text-align:right;">
0.09
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
0.55
</td>
<td style="text-align:right;">
0.68
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:left;">
▁▅▇▅▂
</td>
</tr>
<tr>
<td style="text-align:left;">
percent_married
</td>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
0.63
</td>
<td style="text-align:right;">
0.20
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.52
</td>
<td style="text-align:right;">
0.67
</td>
<td style="text-align:right;">
0.78
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:left;">
▁▂▅▇▃
</td>
</tr>
<tr>
<td style="text-align:left;">
median_income
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
52026.91
</td>
<td style="text-align:right;">
24228.06
</td>
<td style="text-align:right;">
3589.00
</td>
<td style="text-align:right;">
36597.25
</td>
<td style="text-align:right;">
46833.50
</td>
<td style="text-align:right;">
61369.25
</td>
<td style="text-align:right;">
226181.00
</td>
<td style="text-align:left;">
▇▆▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
average_act
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
20.18
</td>
<td style="text-align:right;">
2.60
</td>
<td style="text-align:right;">
-3.07
</td>
<td style="text-align:right;">
18.60
</td>
<td style="text-align:right;">
20.40
</td>
<td style="text-align:right;">
21.91
</td>
<td style="text-align:right;">
32.36
</td>
<td style="text-align:left;">
▁▁▂▇▁
</td>
</tr>
<tr>
<td style="text-align:left;">
percent_lunch
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
0.42
</td>
<td style="text-align:right;">
0.24
</td>
<td style="text-align:right;">
-0.05
</td>
<td style="text-align:right;">
0.24
</td>
<td style="text-align:right;">
0.38
</td>
<td style="text-align:right;">
0.58
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:left;">
▃▇▆▃▂
</td>
</tr>
<tr>
<td style="text-align:left;">
zip_code
</td>
<td style="text-align:right;">
88
</td>
<td style="text-align:right;">
0.99
</td>
<td style="text-align:right;">
44851.47
</td>
<td style="text-align:right;">
24059.23
</td>
<td style="text-align:right;">
1001.00
</td>
<td style="text-align:right;">
28429.25
</td>
<td style="text-align:right;">
45243.00
</td>
<td style="text-align:right;">
62350.00
</td>
<td style="text-align:right;">
99403.00
</td>
<td style="text-align:left;">
▆▆▇▇▁
</td>
</tr>
</tbody>
</table>
<p>We do not have any missing school IDs because this information is available for any school.</p>
<p>The columns <code>average_act</code> and <code>percent_lunch</code> do not have missing values. This is understandable because this is information on the students in the school.</p>
<p>The four columns that describe socioeconomic properties of the adults in the community do have missing values. However, less than half of one percent of the values are missing for each variable.</p>
<p>There are 88 schools where we do not have the basic school information.</p>
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Find the rows where the missing value occurs in each column.</p>
<details>
<p><summary><strong>Show Coding Hint</strong></summary></p>
<p><code>is.na(edgap)</code> is a set of logical <code>TRUE</code> and <code>FALSE</code> values the same dimension as the data frame that indicates whether a value is <code>NA</code> or not.</p>
<p>The function <code>which</code> gives the location where <code>is.an(edgap)</code> is <code>TRUE</code> within each column if we apply the <code>which</code> function along the 2nd dimension.</p>
</details>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="edgap.html#cb59-1"></a><span class="co">#is.na(edgap) is a set of logical TRUE and FALSE values the same dimension as the data frame that indicates whether a value is NA or not.</span></span>
<span id="cb59-2"><a href="edgap.html#cb59-2"></a><span class="co">#the function `which` gives the location where is.an(edgap) is TRUE within each column because we apply the which function along the 2nd dimension.</span></span>
<span id="cb59-3"><a href="edgap.html#cb59-3"></a></span>
<span id="cb59-4"><a href="edgap.html#cb59-4"></a><span class="kw">apply</span>(<span class="kw">is.na</span>(edgap),<span class="dv">2</span>,which)</span></code></pre></div>
<pre><code>## $id
## integer(0)
## 
## $rate_unemployment
##  [1]  142  143  205  364 1056 1074 2067 2176 2717 2758 2931 3973 4150 6103
## 
## $percent_college
##  [1]  142  205  364 1056 1074 2067 2176 2717 2758 2931 3973 4150 6103
## 
## $percent_married
##  [1]    7  142  143  205  364  465 1056 1074 2067 2176 2313 2419 2593 2717 2758
## [16] 2774 2931 3905 3973 4150 4772 5879 6103 6626 7248
## 
## $median_income
##  [1]  142  143  205  364  465 1056 1074 2067 2176 2419 2593 2717 2758 2931 3973
## [16] 4150 5879 6103 6626 7248
## 
## $average_act
## integer(0)
## 
## $percent_lunch
## integer(0)
## 
## $state
##  [1]  482  483  485  486  487  488  490  507 1088 1428 1444 1458 1468 1575 1649
## [16] 2028 2029 2042 2046 2047 2105 2107 2575 2580 2589 2592 2617 2635 2688 2767
## [31] 2771 2772 2773 2774 2775 2776 2777 2778 2779 2780 2781 2782 2783 2784 2785
## [46] 2786 2787 2788 2932 3001 3127 3487 3544 3830 4397 4660 4662 4665 4737 4766
## [61] 4776 5096 5421 5453 5454 5496 5568 5764 6006 6007 6025 6027 6029 6032 6034
## [76] 6043 6044 6350 6354 6356 6357 6359 6379 6834 6901 7564 7568 7961
## 
## $zip_code
##  [1]  482  483  485  486  487  488  490  507 1088 1428 1444 1458 1468 1575 1649
## [16] 2028 2029 2042 2046 2047 2105 2107 2575 2580 2589 2592 2617 2635 2688 2767
## [31] 2771 2772 2773 2774 2775 2776 2777 2778 2779 2780 2781 2782 2783 2784 2785
## [46] 2786 2787 2788 2932 3001 3127 3487 3544 3830 4397 4660 4662 4665 4737 4766
## [61] 4776 5096 5421 5453 5454 5496 5568 5764 6006 6007 6025 6027 6029 6032 6034
## [76] 6043 6044 6350 6354 6356 6357 6359 6379 6834 6901 7564 7568 7961
## 
## $school_type
##  [1]  482  483  485  486  487  488  490  507 1088 1428 1444 1458 1468 1575 1649
## [16] 2028 2029 2042 2046 2047 2105 2107 2575 2580 2589 2592 2617 2635 2688 2767
## [31] 2771 2772 2773 2774 2775 2776 2777 2778 2779 2780 2781 2782 2783 2784 2785
## [46] 2786 2787 2788 2932 3001 3127 3487 3544 3830 4397 4660 4662 4665 4737 4766
## [61] 4776 5096 5421 5453 5454 5496 5568 5764 6006 6007 6025 6027 6029 6032 6034
## [76] 6043 6044 6350 6354 6356 6357 6359 6379 6834 6901 7564 7568 7961
## 
## $school_level
##  [1]  482  483  485  486  487  488  490  507 1088 1428 1444 1458 1468 1575 1649
## [16] 2028 2029 2042 2046 2047 2105 2107 2575 2580 2589 2592 2617 2635 2688 2767
## [31] 2771 2772 2773 2774 2775 2776 2777 2778 2779 2780 2781 2782 2783 2784 2785
## [46] 2786 2787 2788 2932 3001 3127 3487 3544 3830 4397 4660 4662 4665 4737 4766
## [61] 4776 5096 5421 5453 5454 5496 5568 5764 6006 6007 6025 6027 6029 6032 6034
## [76] 6043 6044 6350 6354 6356 6357 6359 6379 6834 6901 7564 7568 7961</code></pre>
</details>
<p>Now we need to decide how to deal with the <code>NA</code>s. We have a few decisions to make:</p>
<ol style="list-style-type: decimal">
<li>Do we drop rows that have <code>NA</code>s?</li>
<li>Do we replace <code>NA</code>s with something like the mean of the variable?</li>
</ol>
<p>There are some schools that are missing all four of the socioeconomic variables, e.g. at rows 142 and 205. However, many of the schools are missing only a subset of the variables. If we drop rows that have <code>NA</code>s, then we will negatively affect our analysis using the variables where data were present. So, we will not drop the rows in this data set that are missing the socioeconomic variables. We have so few missing values from each value that we will not worry about replacing <code>NA</code>s with some other value. We will selectively omit the <code>NA</code>s when working with those columns.</p>
<p>There are, however, 88 schools where we do not have the school information. This raises the possibility that the information is unreliable. Because we are not able to check from the source, we will omit these rows from the data set.</p>
<p><span class="math inline">\(\rightarrow\)</span> Use the <code>filter</code> function to drop only those rows where the state information is missing.</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="edgap.html#cb61-1"></a>edgap &lt;-<span class="st"> </span>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb61-2"><a href="edgap.html#cb61-2"></a><span class="st">  </span><span class="kw">filter</span>(<span class="kw">is.na</span>(state) <span class="op">==</span><span class="st"> </span><span class="ot">FALSE</span>) </span></code></pre></div>
</details>
<p><br></p>
<p>Recheck for missing values:</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="edgap.html#cb62-1"></a><span class="kw">skim</span>(edgap)</span></code></pre></div>
<table style='width: auto;'
        class='table table-condensed'>
<caption>
<span id="tab:unnamed-chunk-33">Table 2.3: </span>Data summary
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
edgap
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
7898
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
11
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
7
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
empty
</th>
<th style="text-align:right;">
n_unique
</th>
<th style="text-align:right;">
whitespace
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
id
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
7898
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
state
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
school_type
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
school_level
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
rate_unemployment
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.10
</td>
<td style="text-align:right;">
0.06
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.06
</td>
<td style="text-align:right;">
0.09
</td>
<td style="text-align:right;">
0.12
</td>
<td style="text-align:right;">
0.59
</td>
<td style="text-align:left;">
▇▃▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
percent_college
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.57
</td>
<td style="text-align:right;">
0.17
</td>
<td style="text-align:right;">
0.09
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
0.56
</td>
<td style="text-align:right;">
0.68
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:left;">
▁▅▇▅▂
</td>
</tr>
<tr>
<td style="text-align:left;">
percent_married
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.64
</td>
<td style="text-align:right;">
0.20
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.53
</td>
<td style="text-align:right;">
0.67
</td>
<td style="text-align:right;">
0.78
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:left;">
▁▂▅▇▃
</td>
</tr>
<tr>
<td style="text-align:left;">
median_income
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
52167.27
</td>
<td style="text-align:right;">
24173.80
</td>
<td style="text-align:right;">
3589.00
</td>
<td style="text-align:right;">
36786.75
</td>
<td style="text-align:right;">
47000.00
</td>
<td style="text-align:right;">
61516.75
</td>
<td style="text-align:right;">
226181.00
</td>
<td style="text-align:left;">
▇▆▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
average_act
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
20.21
</td>
<td style="text-align:right;">
2.57
</td>
<td style="text-align:right;">
-3.07
</td>
<td style="text-align:right;">
18.64
</td>
<td style="text-align:right;">
20.40
</td>
<td style="text-align:right;">
21.94
</td>
<td style="text-align:right;">
32.36
</td>
<td style="text-align:left;">
▁▁▂▇▁
</td>
</tr>
<tr>
<td style="text-align:left;">
percent_lunch
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.42
</td>
<td style="text-align:right;">
0.24
</td>
<td style="text-align:right;">
-0.05
</td>
<td style="text-align:right;">
0.24
</td>
<td style="text-align:right;">
0.38
</td>
<td style="text-align:right;">
0.57
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:left;">
▃▇▆▃▂
</td>
</tr>
<tr>
<td style="text-align:left;">
zip_code
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
44851.47
</td>
<td style="text-align:right;">
24059.23
</td>
<td style="text-align:right;">
1001.00
</td>
<td style="text-align:right;">
28429.25
</td>
<td style="text-align:right;">
45243.00
</td>
<td style="text-align:right;">
62350.00
</td>
<td style="text-align:right;">
99403.00
</td>
<td style="text-align:left;">
▆▆▇▇▁
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="are-there-data-points-that-look-like-errors" class="section level3">
<h3><span class="header-section-number">2.3.7</span> Are there data points that look like errors?</h3>
<p>We will do some quality control for the data set.</p>
<p>We can check the range of each variable to see that the values fall in the expected ranges.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="edgap.html#cb63-1"></a><span class="kw">summary</span>(edgap)</span></code></pre></div>
<pre><code>##       id            rate_unemployment percent_college   percent_married 
##  Length:7898        Min.   :0.00000   Min.   :0.09149   Min.   :0.0000  
##  Class :character   1st Qu.:0.05854   1st Qu.:0.45120   1st Qu.:0.5261  
##  Mode  :character   Median :0.08523   Median :0.55572   Median :0.6686  
##                     Mean   :0.09806   Mean   :0.56938   Mean   :0.6354  
##                     3rd Qu.:0.12272   3rd Qu.:0.67719   3rd Qu.:0.7778  
##                     Max.   :0.59028   Max.   :1.00000   Max.   :1.0000  
##                     NA&#39;s   :14        NA&#39;s   :13        NA&#39;s   :24      
##  median_income     average_act     percent_lunch         state          
##  Min.   :  3589   Min.   :-3.071   Min.   :-0.05455   Length:7898       
##  1st Qu.: 36787   1st Qu.:18.639   1st Qu.: 0.23772   Class :character  
##  Median : 47000   Median :20.400   Median : 0.37904   Mode  :character  
##  Mean   : 52167   Mean   :20.211   Mean   : 0.41824                     
##  3rd Qu.: 61517   3rd Qu.:21.935   3rd Qu.: 0.57060                     
##  Max.   :226181   Max.   :32.363   Max.   : 0.99873                     
##  NA&#39;s   :20                                                             
##     zip_code     school_type        school_level      
##  Min.   : 1001   Length:7898        Length:7898       
##  1st Qu.:28429   Class :character   Class :character  
##  Median :45243   Mode  :character   Mode  :character  
##  Mean   :44851                                        
##  3rd Qu.:62350                                        
##  Max.   :99403                                        
## </code></pre>
<p>There are a few suspicious values. The minimum <code>average_act</code> is -3.071, but ACT scores must be non-negative. Similarly, the minimum <code>percent_lunch</code> is -0.05455, but a percent must be non-negative. We do not have access to information about how these particular data points were generated, so we will remove them from the data set by converting them to <code>NA</code>.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="edgap.html#cb65-1"></a><span class="co">#Number of NA ACT scores before conversion</span></span>
<span id="cb65-2"><a href="edgap.html#cb65-2"></a><span class="kw">sum</span>(<span class="kw">is.na</span>(edgap<span class="op">$</span>average_act))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="edgap.html#cb67-1"></a><span class="co">#Convert negative scores to NA</span></span>
<span id="cb67-2"><a href="edgap.html#cb67-2"></a>edgap[edgap<span class="op">$</span>average_act <span class="op">&lt;</span><span class="st"> </span><span class="dv">0</span>,<span class="st">&quot;average_act&quot;</span>] =<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb67-3"><a href="edgap.html#cb67-3"></a></span>
<span id="cb67-4"><a href="edgap.html#cb67-4"></a><span class="co">#Number of NA ACT scores after conversion</span></span>
<span id="cb67-5"><a href="edgap.html#cb67-5"></a><span class="kw">sum</span>(<span class="kw">is.na</span>(edgap<span class="op">$</span>average_act))</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>There were 3 schools with negative ACT scores, where the values were omitted from the data set.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="edgap.html#cb69-1"></a><span class="co">#Number of NA percent_lunch values before conversion</span></span>
<span id="cb69-2"><a href="edgap.html#cb69-2"></a><span class="kw">sum</span>(<span class="kw">is.na</span>(edgap<span class="op">$</span>percent_lunch))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="edgap.html#cb71-1"></a><span class="co">#Convert negative values to NA</span></span>
<span id="cb71-2"><a href="edgap.html#cb71-2"></a>edgap[edgap<span class="op">$</span>percent_lunch <span class="op">&lt;</span><span class="st"> </span><span class="dv">0</span>,<span class="st">&quot;percent_lunch&quot;</span>] =<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb71-3"><a href="edgap.html#cb71-3"></a></span>
<span id="cb71-4"><a href="edgap.html#cb71-4"></a><span class="co">#Number of NA percent_lunch values after conversion</span></span>
<span id="cb71-5"><a href="edgap.html#cb71-5"></a><span class="kw">sum</span>(<span class="kw">is.na</span>(edgap<span class="op">$</span>percent_lunch))</span></code></pre></div>
<pre><code>## [1] 20</code></pre>
<p>There were 20 schools with negative percent free or reduced lunch, where the values were omitted from the data set.</p>
</div>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2><span class="header-section-number">2.4</span> Exploratory data analysis</h2>
<p>We have two main goals when doing exploratory data analysis. The first is that we want to understand the data set more completely. The second goal is to explore relationships between the variables to help guide the modeling process to answer our specific question.</p>
<div id="graphical-summaries" class="section level3">
<h3><span class="header-section-number">2.4.1</span> Graphical summaries</h3>
<p>Make a pairs plot of the ACT scores and the socioeconomic variables. We will use the <code>ggpairs</code> function from the <code>GGally</code> package.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="edgap.html#cb73-1"></a><span class="co">#It may take a few seconds to produce the plot</span></span>
<span id="cb73-2"><a href="edgap.html#cb73-2"></a></span>
<span id="cb73-3"><a href="edgap.html#cb73-3"></a>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb73-4"><a href="edgap.html#cb73-4"></a><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span><span class="kw">c</span>(id,state,zip_code,school_type,school_level)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb73-5"><a href="edgap.html#cb73-5"></a><span class="st">  </span><span class="kw">ggpairs</span>(<span class="dt">lower =</span> <span class="kw">list</span>(<span class="dt">continuous=</span><span class="kw">wrap</span>(<span class="st">&quot;smooth&quot;</span>))) <span class="op">+</span></span>
<span id="cb73-6"><a href="edgap.html#cb73-6"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<div id="distributions-of-individual-numerical-variables" class="section level4">
<h4><span class="header-section-number">2.4.1.1</span> Distributions of individual numerical variables</h4>
<p><span class="math inline">\(\rightarrow\)</span> Describe the shape of the distribution of each variable.</p>
<details>
<p><summary><strong>Show Answer</strong></summary>
We examine the density plots along the main diagonal of the pairs plots.</p>
<p>All distributions appear to be unimodal.</p>
<p><code>rate_unemployment</code> has a positively skewed distribution. The values near 0.6 may be outliers.</p>
<p><code>percent_college</code> has a roughly symmetric distribution.</p>
<p><code>percent_married</code> has a negatively skewed distribution.</p>
<p><code>average_act</code> has an approximately normal distribution. This is not surprising for a distribution of averages.</p>
<p><code>median_income</code> has a positively skewed distribution, which is what you expect for income distributions.</p>
<p><code>percent_lunch</code> has a slightly positively skewed distribution.</p>
</details>
</div>
<div id="categorical-variables" class="section level4">
<h4><span class="header-section-number">2.4.1.2</span> Categorical variables</h4>
<p>What states are present in the data set and with what frequency?</p>
<span class="math inline">\(\rightarrow\)</span> First find the states present.
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="edgap.html#cb74-1"></a>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb74-2"><a href="edgap.html#cb74-2"></a><span class="st">  </span><span class="kw">select</span>(state) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb74-3"><a href="edgap.html#cb74-3"></a><span class="st">  </span><span class="kw">unique</span>()</span></code></pre></div>
<pre><code>## # A tibble: 20 x 1
##    state
##    &lt;chr&gt;
##  1 DE   
##  2 FL   
##  3 GA   
##  4 IL   
##  5 IN   
##  6 KY   
##  7 LA   
##  8 MA   
##  9 MI   
## 10 MO   
## 11 NJ   
## 12 NY   
## 13 NC   
## 14 OH   
## 15 PA   
## 16 TN   
## 17 TX   
## 18 WA   
## 19 WI   
## 20 WY</code></pre>
There are 20 states represented in the data set.
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Now count the observations by state. Display the results as a bar graph.</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="edgap.html#cb76-1"></a>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb76-2"><a href="edgap.html#cb76-2"></a><span class="st">  </span><span class="kw">count</span>(state) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb76-3"><a href="edgap.html#cb76-3"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> state, <span class="dt">y =</span> n)) <span class="op">+</span></span>
<span id="cb76-4"><a href="edgap.html#cb76-4"></a><span class="st">  </span><span class="kw">geom_col</span>() <span class="op">+</span></span>
<span id="cb76-5"><a href="edgap.html#cb76-5"></a><span class="st">  </span><span class="kw">coord_flip</span>() <span class="op">+</span></span>
<span id="cb76-6"><a href="edgap.html#cb76-6"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;State&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Count&quot;</span>) <span class="op">+</span></span>
<span id="cb76-7"><a href="edgap.html#cb76-7"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Reorder the states by count using <code>fct_reorder</code></p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="edgap.html#cb77-1"></a>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb77-2"><a href="edgap.html#cb77-2"></a><span class="st">  </span><span class="kw">count</span>(state) <span class="op">%&gt;%</span></span>
<span id="cb77-3"><a href="edgap.html#cb77-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">state =</span> <span class="kw">fct_reorder</span>(state, n)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb77-4"><a href="edgap.html#cb77-4"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> state, <span class="dt">y =</span> n)) <span class="op">+</span></span>
<span id="cb77-5"><a href="edgap.html#cb77-5"></a><span class="st">  </span><span class="kw">geom_col</span>() <span class="op">+</span></span>
<span id="cb77-6"><a href="edgap.html#cb77-6"></a><span class="st">  </span><span class="kw">coord_flip</span>() <span class="op">+</span></span>
<span id="cb77-7"><a href="edgap.html#cb77-7"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;State&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Count&quot;</span>) <span class="op">+</span></span>
<span id="cb77-8"><a href="edgap.html#cb77-8"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-40-1.png" width="672" />
There is not an equal number of schools from the represented states.</p>
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> What school types are present in the data set and with what frequency? Present the results as a table and as a bar graph.</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="edgap.html#cb78-1"></a>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb78-2"><a href="edgap.html#cb78-2"></a><span class="st">  </span><span class="kw">count</span>(school_type) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb78-3"><a href="edgap.html#cb78-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">proportion =</span> <span class="kw">round</span>(n<span class="op">/</span><span class="kw">sum</span>(n),<span class="dv">3</span>))</span></code></pre></div>
<pre><code>## # A tibble: 4 x 3
##   school_type                     n proportion
##   &lt;chr&gt;                       &lt;int&gt;      &lt;dbl&gt;
## 1 Alternative School             10      0.001
## 2 Career and Technical School     1      0    
## 3 Regular School               7885      0.998
## 4 Special Education School        2      0</code></pre>
<p>The vast majority (99.8%) are regular schools, but there are a few other types of schools.</p>
<p>We can also present the information as a graph:</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="edgap.html#cb80-1"></a>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb80-2"><a href="edgap.html#cb80-2"></a><span class="st">  </span><span class="kw">count</span>(school_type) <span class="op">%&gt;%</span></span>
<span id="cb80-3"><a href="edgap.html#cb80-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">school_type =</span> <span class="kw">fct_reorder</span>(school_type, n)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb80-4"><a href="edgap.html#cb80-4"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> school_type, <span class="dt">y =</span> n)) <span class="op">+</span></span>
<span id="cb80-5"><a href="edgap.html#cb80-5"></a><span class="st">  </span><span class="kw">geom_col</span>() <span class="op">+</span></span>
<span id="cb80-6"><a href="edgap.html#cb80-6"></a><span class="st">  </span><span class="kw">coord_flip</span>() <span class="op">+</span></span>
<span id="cb80-7"><a href="edgap.html#cb80-7"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;School type&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Count&quot;</span>) <span class="op">+</span></span>
<span id="cb80-8"><a href="edgap.html#cb80-8"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<img src="bookdown-demo_files/figure-html/unnamed-chunk-42-1.png" width="672" />
but the graph can be misleading because of the large number of regular schools and the few schools of the other types.
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> What school levels are present in the data set and with what frequency? Present the results as a table and as a bar graph.</p>
<details>
<p><summary><strong>Show Answer</strong></summary>
As a table:</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="edgap.html#cb81-1"></a>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb81-2"><a href="edgap.html#cb81-2"></a><span class="st">  </span><span class="kw">count</span>(school_level) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb81-3"><a href="edgap.html#cb81-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">proportion =</span> <span class="kw">round</span>(n<span class="op">/</span><span class="kw">sum</span>(n),<span class="dv">3</span>))</span></code></pre></div>
<pre><code>## # A tibble: 4 x 3
##   school_level     n proportion
##   &lt;chr&gt;        &lt;int&gt;      &lt;dbl&gt;
## 1 Elementary       2      0    
## 2 High          7230      0.915
## 3 Not reported    35      0.004
## 4 Other          631      0.08</code></pre>
<p>As a graph:</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="edgap.html#cb83-1"></a>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb83-2"><a href="edgap.html#cb83-2"></a><span class="st">  </span><span class="kw">count</span>(school_level) <span class="op">%&gt;%</span></span>
<span id="cb83-3"><a href="edgap.html#cb83-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">school_level =</span> <span class="kw">fct_reorder</span>(school_level, n)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb83-4"><a href="edgap.html#cb83-4"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> school_level, <span class="dt">y =</span> n)) <span class="op">+</span></span>
<span id="cb83-5"><a href="edgap.html#cb83-5"></a><span class="st">  </span><span class="kw">geom_col</span>() <span class="op">+</span></span>
<span id="cb83-6"><a href="edgap.html#cb83-6"></a><span class="st">  </span><span class="kw">coord_flip</span>() <span class="op">+</span></span>
<span id="cb83-7"><a href="edgap.html#cb83-7"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;School level&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Count&quot;</span>) <span class="op">+</span></span>
<span id="cb83-8"><a href="edgap.html#cb83-8"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
<p>Most of the schools are high schools, but there are some schools listed as <code>Other</code> and <code>Not reported</code>.</p>
</details>
</div>
<div id="focus-on-relationships-with-average_act" class="section level4">
<h4><span class="header-section-number">2.4.1.3</span> Focus on relationships with <code>average_act</code></h4>
<p>Our primary goal is to determine whether there is a relationship between the socioeconomic variables and <code>average_act</code>, so we will make plots to focus on those relationships.</p>
<p>The largest correlation coefficient between a socioeconomic variable and <code>average_act</code> is for <code>percent_lunch</code>, so we will start there.</p>
<p><span class="math inline">\(\rightarrow\)</span> Make a scatter plot of <code>percent_lunch</code> and <code>average_act</code></p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="edgap.html#cb84-1"></a><span class="kw">ggplot</span>(edgap, <span class="kw">aes</span>(<span class="dt">x =</span> percent_lunch, <span class="dt">y =</span> average_act)) <span class="op">+</span></span>
<span id="cb84-2"><a href="edgap.html#cb84-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb84-3"><a href="edgap.html#cb84-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&#39;Percent reduced or free lunch&#39;</span>, <span class="dt">y =</span> <span class="st">&#39;Average school ACT or equivalent if SAT&#39;</span>) <span class="op">+</span></span>
<span id="cb84-4"><a href="edgap.html#cb84-4"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 23 rows containing missing values (geom_point).</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<p>There is a clear negative linear association between <code>percent_lunch</code> and <code>average_act</code>.</p>
<p>Why is there a wide range of ACT scores at <code>percent_lunch</code> = 0? It may be the case that some schools have no students receiving free or reduced lunch because the program does not exist, not because there are no families that would qualify under typical standards. This would require further research into the availability of the free or reduced price lunch program.</p>
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Make a scatter plot of <code>median_income</code> and <code>average_act</code></p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="edgap.html#cb86-1"></a><span class="kw">ggplot</span>(edgap, <span class="kw">aes</span>(<span class="dt">x =</span> median_income, <span class="dt">y =</span> average_act)) <span class="op">+</span></span>
<span id="cb86-2"><a href="edgap.html#cb86-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb86-3"><a href="edgap.html#cb86-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&#39;Median income ($)&#39;</span>, <span class="dt">y =</span> <span class="st">&#39;Average school ACT or equivalent if SAT&#39;</span> ) <span class="op">+</span></span>
<span id="cb86-4"><a href="edgap.html#cb86-4"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 23 rows containing missing values (geom_point).</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
<p>There is a positive association between <code>median_income</code> and <code>average_act</code>. The form of the association appears to be nonlinear.</p>
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> <code>median_income</code> has a skewed distribution, so make a scatter plot with <code>median_income</code> plotted on a log scale.</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="edgap.html#cb88-1"></a><span class="kw">ggplot</span>(edgap, <span class="kw">aes</span>(<span class="dt">x =</span> median_income, <span class="dt">y =</span> average_act)) <span class="op">+</span></span>
<span id="cb88-2"><a href="edgap.html#cb88-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb88-3"><a href="edgap.html#cb88-3"></a><span class="st">  </span><span class="kw">scale_x_log10</span>() <span class="op">+</span></span>
<span id="cb88-4"><a href="edgap.html#cb88-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&#39;Median income ($)&#39;</span>, <span class="dt">y =</span> <span class="st">&#39;Average school ACT or equivalent if SAT&#39;</span> ) <span class="op">+</span></span>
<span id="cb88-5"><a href="edgap.html#cb88-5"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 23 rows containing missing values (geom_point).</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<p>There is a positive linear associate between the log of <code>median_income</code> and <code>average_act</code>. Note also that the typical regression assumption of equal variance of errors is closer to being satisfied after the log transformation.</p>
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Make a scatter plot of <code>percent_college</code> and <code>average_act</code></p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="edgap.html#cb90-1"></a><span class="kw">ggplot</span>(edgap, <span class="kw">aes</span>(<span class="dt">x =</span> percent_college, <span class="dt">y =</span> average_act)) <span class="op">+</span></span>
<span id="cb90-2"><a href="edgap.html#cb90-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb90-3"><a href="edgap.html#cb90-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&#39;Percent college&#39;</span>, <span class="dt">y =</span> <span class="st">&#39;Average school ACT or equivalent if SAT&#39;</span>) <span class="op">+</span></span>
<span id="cb90-4"><a href="edgap.html#cb90-4"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 16 rows containing missing values (geom_point).</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>There is a positive association between <code>percent_college</code> and <code>average_act</code>. There may be a nonlinear component to the association, but it is difficult to assess visually from the scatter plot.</p>
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Make a scatter plot of <code>percent_married</code> and <code>average_act</code></p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="edgap.html#cb92-1"></a><span class="kw">ggplot</span>(edgap, <span class="kw">aes</span>(<span class="dt">x =</span> percent_married, <span class="dt">y =</span> average_act)) <span class="op">+</span></span>
<span id="cb92-2"><a href="edgap.html#cb92-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb92-3"><a href="edgap.html#cb92-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&#39;Percent college&#39;</span>, <span class="dt">y =</span> <span class="st">&#39;Average school ACT or equivalent if SAT&#39;</span>) <span class="op">+</span></span>
<span id="cb92-4"><a href="edgap.html#cb92-4"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 27 rows containing missing values (geom_point).</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-49-1.png" width="672" /></p>
<p>There is a positive association between <code>percent_married</code> and <code>average_act</code>.</p>
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Make a scatter plot of <code>rate_unemployment</code> and <code>average_act</code></p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="edgap.html#cb94-1"></a><span class="kw">ggplot</span>(edgap, <span class="kw">aes</span>(<span class="dt">x =</span> rate_unemployment, <span class="dt">y =</span> average_act)) <span class="op">+</span></span>
<span id="cb94-2"><a href="edgap.html#cb94-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb94-3"><a href="edgap.html#cb94-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&#39;Rate of unemployment&#39;</span>, <span class="dt">y =</span> <span class="st">&#39;Average school ACT or equivalent if SAT&#39;</span>) <span class="op">+</span></span>
<span id="cb94-4"><a href="edgap.html#cb94-4"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 17 rows containing missing values (geom_point).</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-50-1.png" width="672" />
There is a negative association between <code>rate_unemployment</code> and <code>average_act</code>.</p>
</details>
<p><br></p>
<p><code>rate_unemployment</code> has a positively skewed distribution, so we should make a scatter plot on a transformed scale. There are values of <code>rate_unemployment</code> that are equal to zero,</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="edgap.html#cb96-1"></a><span class="kw">min</span>(edgap<span class="op">$</span>rate_unemployment, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>so we will use a square root transformation, rather than a log transformation.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="edgap.html#cb98-1"></a><span class="kw">library</span>(latex2exp) <span class="co">#This library is used for LaTex in the axis labels</span></span>
<span id="cb98-2"><a href="edgap.html#cb98-2"></a></span>
<span id="cb98-3"><a href="edgap.html#cb98-3"></a>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb98-4"><a href="edgap.html#cb98-4"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">sqrt</span>(rate_unemployment), <span class="dt">y =</span> average_act)) <span class="op">+</span></span>
<span id="cb98-5"><a href="edgap.html#cb98-5"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb98-6"><a href="edgap.html#cb98-6"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">TeX</span>(<span class="st">&#39;$</span><span class="ch">\\</span><span class="st">sqrt{$Rate of unemployment$}$&#39;</span>), <span class="dt">y =</span> <span class="st">&#39;Average school ACT or equivalent if SAT&#39;</span>) <span class="op">+</span></span>
<span id="cb98-7"><a href="edgap.html#cb98-7"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 17 rows containing missing values (geom_point).</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
</div>
<div id="numerical-summaries" class="section level4">
<h4><span class="header-section-number">2.4.1.4</span> Numerical summaries</h4>
<p>Use the <code>skim</code> function to examine the basic numerical summaries for each variable.</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="edgap.html#cb100-1"></a>edgap <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="op">-</span>id) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">skim</span>()</span></code></pre></div>
<table style='width: auto;'
        class='table table-condensed'>
<caption>
<span id="tab:unnamed-chunk-53">Table 2.4: </span>Data summary
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
Piped data
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
7898
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
10
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
7
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
empty
</th>
<th style="text-align:right;">
n_unique
</th>
<th style="text-align:right;">
whitespace
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
state
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
school_type
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
school_level
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
rate_unemployment
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.10
</td>
<td style="text-align:right;">
0.06
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.06
</td>
<td style="text-align:right;">
0.09
</td>
<td style="text-align:right;">
0.12
</td>
<td style="text-align:right;">
0.59
</td>
<td style="text-align:left;">
▇▃▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
percent_college
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.57
</td>
<td style="text-align:right;">
0.17
</td>
<td style="text-align:right;">
0.09
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
0.56
</td>
<td style="text-align:right;">
0.68
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:left;">
▁▅▇▅▂
</td>
</tr>
<tr>
<td style="text-align:left;">
percent_married
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.64
</td>
<td style="text-align:right;">
0.20
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.53
</td>
<td style="text-align:right;">
0.67
</td>
<td style="text-align:right;">
0.78
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:left;">
▁▂▅▇▃
</td>
</tr>
<tr>
<td style="text-align:left;">
median_income
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
52167.27
</td>
<td style="text-align:right;">
24173.80
</td>
<td style="text-align:right;">
3589.00
</td>
<td style="text-align:right;">
36786.75
</td>
<td style="text-align:right;">
47000.00
</td>
<td style="text-align:right;">
61516.75
</td>
<td style="text-align:right;">
226181.00
</td>
<td style="text-align:left;">
▇▆▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
average_act
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
20.22
</td>
<td style="text-align:right;">
2.53
</td>
<td style="text-align:right;">
12.36
</td>
<td style="text-align:right;">
18.65
</td>
<td style="text-align:right;">
20.40
</td>
<td style="text-align:right;">
21.94
</td>
<td style="text-align:right;">
32.36
</td>
<td style="text-align:left;">
▂▇▇▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
percent_lunch
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.42
</td>
<td style="text-align:right;">
0.24
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.24
</td>
<td style="text-align:right;">
0.38
</td>
<td style="text-align:right;">
0.57
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:left;">
▅▇▆▃▂
</td>
</tr>
<tr>
<td style="text-align:left;">
zip_code
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
44851.47
</td>
<td style="text-align:right;">
24059.23
</td>
<td style="text-align:right;">
1001.00
</td>
<td style="text-align:right;">
28429.25
</td>
<td style="text-align:right;">
45243.00
</td>
<td style="text-align:right;">
62350.00
</td>
<td style="text-align:right;">
99403.00
</td>
<td style="text-align:left;">
▆▆▇▇▁
</td>
</tr>
</tbody>
</table>
</details>
</div>
</div>
</div>
<div id="model" class="section level2">
<h2><span class="header-section-number">2.5</span> Model</h2>
<p>Our exploratory data analysis has led to the following observations that will help guide the modeling process:</p>
<ol style="list-style-type: decimal">
<li>Each of the socioeconomic variables is associated with the ACT score and is worthwhile to consider as a predictor.</li>
<li>Some of the socioeconomic variables may have a nonlinear relationship with the ACT score, so nonlinear models should be explored.</li>
<li>The socioeconomic variables are correlated with each other, so the best prediction of ACT score might not include all socioeconomic variables.</li>
</ol>
<div id="simple-linear-regression-with-each-socioeconomic-predictor" class="section level3">
<h3><span class="header-section-number">2.5.1</span> Simple linear regression with each socioeconomic predictor</h3>
<p>In this project, we are very concerned with understanding the relationships in the data set; we are not only concerned with building a model with the highest prediction accuracy. Therefore, we will start by looking at simple linear regression models using each socioeconomic predictor.</p>
<div id="percent-free-or-reduced-lunch" class="section level4">
<h4><span class="header-section-number">2.5.1.1</span> Percent free or reduced lunch</h4>
<p><strong>Fit a model</strong></p>
<p>We want to fit the simple linear regression model</p>
<p><code>average_act</code> <span class="math inline">\(\approx \beta_0 + \beta_1\)</span> <code>percent_lunch</code></p>
<p>Use the function <code>lm</code> to fit a simple linear regression model.</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="edgap.html#cb101-1"></a>fit_pl &lt;-<span class="st"> </span><span class="kw">lm</span>(average_act <span class="op">~</span><span class="st"> </span>percent_lunch, <span class="dt">data =</span> edgap)</span></code></pre></div>
<p>Use the <code>summary</code> function to</p>
<ol style="list-style-type: decimal">
<li>Interpret the coefficients in the model.</li>
<li>Assess the statistical significance of the coefficient on the predictor variable.</li>
</ol>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="edgap.html#cb102-1"></a><span class="kw">summary</span>(fit_pl)<span class="op">$</span>coefficients</span></code></pre></div>
<pre><code>##                Estimate Std. Error   t value Pr(&gt;|t|)
## (Intercept)   23.707902 0.03615481  655.7330        0
## percent_lunch -8.318337 0.07503489 -110.8596        0</code></pre>
<p>The intercept is 23.7 and the slope is -8.32. The intercept is interpreted as the best estimate for the mean ACT score when <code>percent_lunch</code> is zero. The slope can be interpreted as saying that a <code>percent_lunch</code> increase of 0.1 is associated with a decrease in the estimated mean ACT score of -0.832 points.</p>
<p>The slope is highly statistically significant, as the p-values are reported as zero. So, there is a statistically significant relationship between <code>percent_lunch</code> and the average ACT score in a school.</p>
<p>Plot the regression line together with the scatter plot</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="edgap.html#cb104-1"></a><span class="co">#geom_smooth(method = &quot;lm&quot;,formula = y ~ x) adds the regression line to the scatter plot</span></span>
<span id="cb104-2"><a href="edgap.html#cb104-2"></a></span>
<span id="cb104-3"><a href="edgap.html#cb104-3"></a><span class="kw">ggplot</span>(edgap, <span class="kw">aes</span>(<span class="dt">x =</span> percent_lunch, <span class="dt">y =</span> average_act)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb104-4"><a href="edgap.html#cb104-4"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb104-5"><a href="edgap.html#cb104-5"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>,<span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x) <span class="op">+</span></span>
<span id="cb104-6"><a href="edgap.html#cb104-6"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Percent free or reduced lunch&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;School ACT average (or equivalent if SAT score)&quot;</span>) <span class="op">+</span></span>
<span id="cb104-7"><a href="edgap.html#cb104-7"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-56-1.png" width="672" /></p>
<p><strong>Assess the accuracy of the fit</strong></p>
<p>Examine the <span class="math inline">\(R^2\)</span> and the residual standard error</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="edgap.html#cb105-1"></a><span class="kw">summary</span>(fit_pl)<span class="op">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.6095294</code></pre>
<p>The simple linear regression model using percent free or reduced lunch as a predictor can explain 61% in the variance of the ACT score.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="edgap.html#cb107-1"></a><span class="kw">summary</span>(fit_pl)<span class="op">$</span>sigma</span></code></pre></div>
<pre><code>## [1] 1.582026</code></pre>
<p>The residual standard error is 1.58 points. This means that the model is off by about 1.58 points, on average.</p>
<p>Together, these results show that we can make a good prediction of the average ACT score in a school only by knowing the percent of students receiving free or reduced lunch.</p>
<p>Note that, in this example, we called different components from the <code>summary</code> output individually. We took this approach to walk through each step of the analysis, but you can simply look at the output of <code>summary(fit_pl)</code> to see all of the information at once.</p>
<p><strong>Residual plot</strong></p>
<p>Examine a residual plot to see if we can improve the model through a transformation of the <code>percent_lunch</code> variable.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="edgap.html#cb109-1"></a><span class="co">#We will use ggplot2 to make the residual plot. You can also use plot(fit_pl) </span></span>
<span id="cb109-2"><a href="edgap.html#cb109-2"></a><span class="kw">ggplot</span>(fit_pl,<span class="kw">aes</span>(<span class="dt">x=</span>percent_lunch, <span class="dt">y=</span>.resid)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb109-3"><a href="edgap.html#cb109-3"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb109-4"><a href="edgap.html#cb109-4"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;loess&quot;</span>, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x) <span class="op">+</span></span>
<span id="cb109-5"><a href="edgap.html#cb109-5"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Percent free or reduced lunch&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Residuals&quot;</span>) <span class="op">+</span></span>
<span id="cb109-6"><a href="edgap.html#cb109-6"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<p>The residual plot does not have much systematic structure, so we have used <code>percent_lunch</code> as well as we can as a predictor. We do not need to consider a more complicated model.</p>
</div>
<div id="median-income" class="section level4">
<h4><span class="header-section-number">2.5.1.2</span> Median income</h4>
<p><strong>Fit a model</strong></p>
<p>We want to fit the simple linear regression model</p>
<p><code>average_act</code> <span class="math inline">\(\approx \beta_0 + \beta_1\)</span> <code>median_income</code></p>
<p><span class="math inline">\(\rightarrow\)</span> Use the function <code>lm</code> to fit a simple linear regression model.</p>
<details>
<p><summary><span style="color: gray;"><strong>Show Answer</strong></span></summary></p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="edgap.html#cb110-1"></a>fit_mi &lt;-<span class="st"> </span><span class="kw">lm</span>(average_act <span class="op">~</span><span class="st"> </span>median_income, <span class="dt">data =</span> edgap)</span></code></pre></div>
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Use the <code>summary</code> function to:</p>
<ol style="list-style-type: decimal">
<li>Interpret the coefficients in the model.</li>
<li>Assess the statistical significance of the coefficient on the predictor variable.</li>
</ol>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="edgap.html#cb111-1"></a><span class="kw">summary</span>(fit_mi)<span class="op">$</span>coefficients</span></code></pre></div>
<pre><code>##                   Estimate   Std. Error   t value Pr(&gt;|t|)
## (Intercept)   1.775617e+01 6.050841e-02 293.44960        0
## median_income 4.720992e-05 1.052248e-06  44.86577        0</code></pre>
<p>The intercept is 17.8 and the slope is <span class="math inline">\(4.7 \times 10^{-5}\)</span>.</p>
<p>The intercept is interpreted as the best estimate for the mean ACT score when <code>median_income</code> is zero. The median income is never equal to zero, so the intercept does not have a clear interpretation in this model.</p>
<p>The slope can be interpreted as saying that a difference of $1 in <code>median_income</code> is associated with a difference in the estimated mean ACT score of <span class="math inline">\(4.7 \times 10^{-5}\)</span> points. This value of the slope is not intuitive because the median income is in dollars, but differences in annual income of several dollars is not meaningful. It would be helpful to represent median income in tens of thousands of dollars to make a one-unit change more meaningful.</p>
<p>We will use the <code>mutate</code> function to add a new variable to the data frame called <code>median_income_10k</code> that represents median income in tens of thousands of dollars.</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="edgap.html#cb113-1"></a>edgap &lt;-<span class="st"> </span>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb113-2"><a href="edgap.html#cb113-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">median_income_10k =</span> median_income<span class="op">/</span><span class="fl">1e4</span>)</span></code></pre></div>
<p>We can refit the model</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="edgap.html#cb114-1"></a>fit_mi &lt;-<span class="st"> </span><span class="kw">lm</span>(average_act <span class="op">~</span><span class="st"> </span>median_income_10k, <span class="dt">data =</span> edgap)</span>
<span id="cb114-2"><a href="edgap.html#cb114-2"></a></span>
<span id="cb114-3"><a href="edgap.html#cb114-3"></a><span class="kw">summary</span>(fit_mi)<span class="op">$</span>coefficients</span></code></pre></div>
<pre><code>##                     Estimate Std. Error   t value Pr(&gt;|t|)
## (Intercept)       17.7561695 0.06050841 293.44960        0
## median_income_10k  0.4720992 0.01052248  44.86577        0</code></pre>
<p>The intercept remains 17.8, but the slope is now 0.47, corresponding to the scaling of the median income units.</p>
<p>The slope can be interpreted as saying that a difference of $10,000 in median income is associated with a difference in the estimated mean ACT score of 0.47 points.</p>
<p>The slope is highly statistically significant. So, there is a statistically significant relationship between median income and the average ACT score in a school.</p>
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Plot the regression line together with the scatter plot</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="edgap.html#cb116-1"></a><span class="kw">ggplot</span>(edgap, <span class="kw">aes</span>(<span class="dt">x =</span> median_income_10k, <span class="dt">y =</span> average_act)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb116-2"><a href="edgap.html#cb116-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb116-3"><a href="edgap.html#cb116-3"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>,<span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x) <span class="op">+</span></span>
<span id="cb116-4"><a href="edgap.html#cb116-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Median Household Income (ten thousand $)&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;School ACT average (or equivalent if SAT score)&quot;</span>) <span class="op">+</span></span>
<span id="cb116-5"><a href="edgap.html#cb116-5"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-64-1.png" width="672" /></p>
</details>
<p><br></p>
<p><strong>Assess the accuracy of the fit</strong></p>
<p><span class="math inline">\(\rightarrow\)</span> Examine the <span class="math inline">\(R^2\)</span> and the residual standard error</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="edgap.html#cb117-1"></a><span class="kw">summary</span>(fit_mi)<span class="op">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.2036162</code></pre>
<p>The simple linear regression model using median income as a predictor explains 20.4% in the variance of the ACT score.</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="edgap.html#cb119-1"></a><span class="kw">summary</span>(fit_mi)<span class="op">$</span>sigma</span></code></pre></div>
<pre><code>## [1] 2.257099</code></pre>
<p>The residual standard error is 2.26 points. This means that the model is off by about 2.26 points, on average.</p>
<p>Together, these results show that we can do some moderate prediction of the average ACT score in a school only by knowing the median income.</p>
</details>
<p><br></p>
<p><strong>Residual plot</strong></p>
<p><span class="math inline">\(\rightarrow\)</span> Examine a residual plot to see if we can improve the model through a transformation of the <code>median_income_10</code> variable.</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="edgap.html#cb121-1"></a><span class="kw">ggplot</span>(fit_mi,<span class="kw">aes</span>(<span class="dt">x=</span>median_income_10k, <span class="dt">y=</span>.resid)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb121-2"><a href="edgap.html#cb121-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb121-3"><a href="edgap.html#cb121-3"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;loess&quot;</span>, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x) <span class="op">+</span></span>
<span id="cb121-4"><a href="edgap.html#cb121-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Median Household Income (ten thousand $)&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Residuals&quot;</span>) <span class="op">+</span></span>
<span id="cb121-5"><a href="edgap.html#cb121-5"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-67-1.png" width="672" /></p>
<p>The residual plot suggests that a nonlinear model may improve the fit.</p>
We will try a log transformation.
</details>
<p><br></p>
<p><strong>Log transformation</strong></p>
<p><strong>Fit the model</strong></p>
<p><span class="math inline">\(\rightarrow\)</span> Fit a linear regression model using the log of <code>median_income_10</code> as the predictor.</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="edgap.html#cb122-1"></a>fit_mi_log &lt;-<span class="st"> </span><span class="kw">lm</span>(average_act <span class="op">~</span><span class="st"> </span><span class="kw">log10</span>(median_income_10k), <span class="dt">data =</span> edgap)</span></code></pre></div>
</details>
<p><br>
<span class="math inline">\(\rightarrow\)</span> Use the <code>summary</code> function to:</p>
<ol style="list-style-type: decimal">
<li>Interpret the coefficients in the model.</li>
<li>Assess the statistical significance of the coefficient on the predictor variable.</li>
</ol>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="edgap.html#cb123-1"></a><span class="kw">summary</span>(fit_mi_log)<span class="op">$</span>coefficients</span></code></pre></div>
<pre><code>##                           Estimate Std. Error   t value Pr(&gt;|t|)
## (Intercept)              16.088163 0.09474785 169.79978        0
## log10(median_income_10k)  6.106566 0.13492785  45.25801        0</code></pre>
<p>The intercept is 16.1. The intercept is interpreted as the prediction of the average ACT score when the predictor is zero, which means that the median income is $10,000.</p>
<p>The slope is 6.1. Because we used a base 10 log, the slope is interpreted as saying that a median income ten times greater than another is associated with an average ACT score that is 6.1 points higher.</p>
The slope is highly statistically significant.
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Plot the regression line together with the scatter plot</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="edgap.html#cb125-1"></a><span class="kw">ggplot</span>(edgap, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">log10</span>(median_income_10k), <span class="dt">y =</span> average_act)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb125-2"><a href="edgap.html#cb125-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb125-3"><a href="edgap.html#cb125-3"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>,<span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x) <span class="op">+</span></span>
<span id="cb125-4"><a href="edgap.html#cb125-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Log of median Household Income&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;School ACT average (or equivalent if SAT score)&quot;</span>) <span class="op">+</span></span>
<span id="cb125-5"><a href="edgap.html#cb125-5"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<img src="bookdown-demo_files/figure-html/unnamed-chunk-70-1.png" width="672" />
</details>
<p><br></p>
<p><strong>Assess the accuracy of the fit</strong></p>
<p><span class="math inline">\(\rightarrow\)</span> Examine the <span class="math inline">\(R^2\)</span> and the residual standard error</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="edgap.html#cb126-1"></a><span class="kw">summary</span>(fit_mi_log)<span class="op">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.2064538</code></pre>
<p>The simple linear regression model using median income as a predictor can explain 20.6% in the variance of the ACT score.</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="edgap.html#cb128-1"></a><span class="kw">summary</span>(fit_mi_log)<span class="op">$</span>sigma</span></code></pre></div>
<pre><code>## [1] 2.253074</code></pre>
<p>The residual standard error is 2.25 points. This means that the model is off by about 2.25 points, on average.</p>
Together, these results show that we can do some moderate prediction of the average ACT score in a school only by knowing the median income.
</details>
<p><br></p>
<p><strong>Residual plot</strong></p>
<p><span class="math inline">\(\rightarrow\)</span> Examine a residual plot to see if we can improve the model through a transformation of the input.</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="edgap.html#cb130-1"></a><span class="kw">ggplot</span>(fit_mi_log,<span class="kw">aes</span>(<span class="dt">x=</span>.fitted, <span class="dt">y=</span>.resid)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb130-2"><a href="edgap.html#cb130-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb130-3"><a href="edgap.html#cb130-3"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;loess&quot;</span>, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x) <span class="op">+</span></span>
<span id="cb130-4"><a href="edgap.html#cb130-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Log Median Household Income&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Residuals&quot;</span>) <span class="op">+</span></span>
<span id="cb130-5"><a href="edgap.html#cb130-5"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-73-1.png" width="672" /></p>
The structure in the residual plot appears to be due to the points near 14. Therefore, we will not consider further transformations.
</details>
</div>
<div id="percent-college" class="section level4">
<h4><span class="header-section-number">2.5.1.3</span> Percent college</h4>
<p><strong>Fit a model</strong></p>
<p>We want to fit the simple linear regression model</p>
<p><code>average_act</code> <span class="math inline">\(\approx \beta_0 + \beta_1\)</span> <code>percent_college</code></p>
<p><span class="math inline">\(\rightarrow\)</span> Use the function <code>lm</code> to fit a simple linear regression model.</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="edgap.html#cb131-1"></a>fit_pc &lt;-<span class="st"> </span><span class="kw">lm</span>(average_act <span class="op">~</span><span class="st"> </span>percent_college, <span class="dt">data =</span> edgap)</span></code></pre></div>
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Use the <code>summary</code> function to</p>
<ol style="list-style-type: decimal">
<li>Interpret the coefficients in the model.</li>
<li>Assess the statistical significance of the coefficient on the predictor variable.</li>
</ol>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="edgap.html#cb132-1"></a><span class="kw">summary</span>(fit_pc)<span class="op">$</span>coefficients</span></code></pre></div>
<pre><code>##                  Estimate Std. Error   t value Pr(&gt;|t|)
## (Intercept)     16.365784 0.09130969 179.23382        0
## percent_college  6.769421 0.15394570  43.97279        0</code></pre>
<p>The slope is highly statistically significant. So, there is a statistically significant relationship between percent college and the average ACT score in a school.</p>
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Plot the regression line together with the scatter plot</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="edgap.html#cb134-1"></a><span class="kw">ggplot</span>(edgap, <span class="kw">aes</span>(<span class="dt">x =</span> percent_college, <span class="dt">y =</span> average_act)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb134-2"><a href="edgap.html#cb134-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb134-3"><a href="edgap.html#cb134-3"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>,<span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x) <span class="op">+</span></span>
<span id="cb134-4"><a href="edgap.html#cb134-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Percent college&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;School ACT average (or equivalent if SAT score)&quot;</span>) <span class="op">+</span></span>
<span id="cb134-5"><a href="edgap.html#cb134-5"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 16 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 16 rows containing missing values (geom_point).</code></pre>
<img src="bookdown-demo_files/figure-html/unnamed-chunk-76-1.png" width="672" />
</details>
<p><br></p>
<p><strong>Assess the accuracy of the fit</strong></p>
<p><span class="math inline">\(\rightarrow\)</span> Examine the <span class="math inline">\(R^2\)</span> and the residual standard error</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="edgap.html#cb137-1"></a><span class="kw">summary</span>(fit_pc)<span class="op">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.1970332</code></pre>
<p>The simple linear regression model using median income as a predictor can explain 19.7% in the variance of the ACT score.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="edgap.html#cb139-1"></a><span class="kw">summary</span>(fit_pc)<span class="op">$</span>sigma</span></code></pre></div>
<pre><code>## [1] 2.266632</code></pre>
<p>The residual standard error is 2.27 points. This means that the model is off by about 2.27 points, on average.</p>
Together, these results show that we can do some moderate prediction of the average ACT score in a school only by knowing the percent of college graduates among adults.
</details>
<p><br></p>
<p><strong>Residual plot</strong></p>
<p><span class="math inline">\(\rightarrow\)</span> Examine a residual plot to see if we can improve the model through a transformation of the input variable.</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="edgap.html#cb141-1"></a><span class="kw">ggplot</span>(fit_pc,<span class="kw">aes</span>(<span class="dt">x=</span>percent_college, <span class="dt">y=</span>.resid)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb141-2"><a href="edgap.html#cb141-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb141-3"><a href="edgap.html#cb141-3"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;loess&quot;</span>, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x) <span class="op">+</span></span>
<span id="cb141-4"><a href="edgap.html#cb141-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Percent college&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Residuals&quot;</span>) <span class="op">+</span></span>
<span id="cb141-5"><a href="edgap.html#cb141-5"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-79-1.png" width="672" /></p>
<p>The residual plot has a small suggestion that a quadratic model might be useful.</p>
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Fit and assess a quadratic model</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="edgap.html#cb142-1"></a>fit_pc_quad &lt;-<span class="st"> </span><span class="kw">lm</span>(average_act <span class="op">~</span><span class="st"> </span><span class="kw">poly</span>(percent_college,<span class="dv">2</span>, <span class="dt">raw =</span> T), <span class="dt">data =</span> edgap)</span></code></pre></div>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="edgap.html#cb143-1"></a><span class="kw">summary</span>(fit_pc_quad)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = average_act ~ poly(percent_college, 2, raw = T), 
##     data = edgap)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.1850 -1.2924  0.2954  1.4954 11.2029 
## 
## Coefficients:
##                                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                         16.0778     0.2572  62.502   &lt;2e-16 ***
## poly(percent_college, 2, raw = T)1   7.8282     0.8976   8.721   &lt;2e-16 ***
## poly(percent_college, 2, raw = T)2  -0.8954     0.7478  -1.197    0.231    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.267 on 7879 degrees of freedom
##   (16 observations deleted due to missingness)
## Multiple R-squared:  0.1972, Adjusted R-squared:  0.197 
## F-statistic: 967.6 on 2 and 7879 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The coefficient on the squared term is not significant, so the quadratic model does not provide an improvement over the linear model.</p>
</details>
<p><br></p>
</div>
<div id="rate-of-unemployment" class="section level4">
<h4><span class="header-section-number">2.5.1.4</span> Rate of unemployment</h4>
<p><strong>Fit a model</strong></p>
<p>We want to fit the simple linear regression model</p>
<p><code>average_act</code> <span class="math inline">\(\approx \beta_0 + \beta_1\)</span> <code>rate_unemployment</code></p>
<p><span class="math inline">\(\rightarrow\)</span> Use the function <code>lm</code> to fit a simple linear regression model.</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="edgap.html#cb145-1"></a>fit_ru &lt;-<span class="st"> </span><span class="kw">lm</span>(average_act <span class="op">~</span><span class="st"> </span>rate_unemployment, <span class="dt">data =</span> edgap)</span></code></pre></div>
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Use the <code>summary</code> function to:</p>
<ol style="list-style-type: decimal">
<li>Interpret the coefficients in the model.</li>
<li>Assess the statistical significance of the coefficient on the predictor variable.</li>
</ol>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="edgap.html#cb146-1"></a><span class="kw">summary</span>(fit_ru)<span class="op">$</span>coefficients</span></code></pre></div>
<pre><code>##                    Estimate Std. Error   t value Pr(&gt;|t|)
## (Intercept)        22.02428 0.05056679 435.54824        0
## rate_unemployment -18.39563 0.44343869 -41.48404        0</code></pre>
The slope is highly statistically significant. So, there is a statistically significant relationship between unemployment rate and the average ACT score in a school.
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Plot the regression line together with the scatter plot</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="edgap.html#cb148-1"></a><span class="kw">ggplot</span>(edgap, <span class="kw">aes</span>(<span class="dt">x =</span> rate_unemployment, <span class="dt">y =</span> average_act)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb148-2"><a href="edgap.html#cb148-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb148-3"><a href="edgap.html#cb148-3"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>,<span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x) <span class="op">+</span></span>
<span id="cb148-4"><a href="edgap.html#cb148-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Unemployment rate&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;School ACT average (or equivalent if SAT score)&quot;</span>) <span class="op">+</span></span>
<span id="cb148-5"><a href="edgap.html#cb148-5"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 17 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 17 rows containing missing values (geom_point).</code></pre>
<img src="bookdown-demo_files/figure-html/unnamed-chunk-84-1.png" width="672" />
</details>
<p><br></p>
<p><strong>Assess the accuracy of the fit</strong></p>
<p><span class="math inline">\(\rightarrow\)</span> Examine the <span class="math inline">\(R^2\)</span> and the residual standard error</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="edgap.html#cb151-1"></a><span class="kw">summary</span>(fit_ru)<span class="op">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.1792644</code></pre>
<p>The simple linear regression model using unemployment rate as a predictor can explain 17.9% in the variance of the ACT score.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="edgap.html#cb153-1"></a><span class="kw">summary</span>(fit_ru)<span class="op">$</span>sigma</span></code></pre></div>
<pre><code>## [1] 2.291589</code></pre>
<p>The residual standard error is 2.29 points. This means that the model is off by about 2.29 points, on average.</p>
Together, these results show that we can do some moderate prediction of the average ACT score in a school only by knowing the unemployment rate.
</details>
<p><br></p>
<p><strong>Residual plot</strong></p>
<p><span class="math inline">\(\rightarrow\)</span> Examine a residual plot to see if we can improve the model.</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="edgap.html#cb155-1"></a><span class="kw">ggplot</span>(fit_ru,<span class="kw">aes</span>(<span class="dt">x=</span>rate_unemployment, <span class="dt">y=</span>.resid)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb155-2"><a href="edgap.html#cb155-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb155-3"><a href="edgap.html#cb155-3"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;loess&quot;</span>, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x) <span class="op">+</span></span>
<span id="cb155-4"><a href="edgap.html#cb155-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Unemployment rate&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Residuals&quot;</span>) <span class="op">+</span></span>
<span id="cb155-5"><a href="edgap.html#cb155-5"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<img src="bookdown-demo_files/figure-html/unnamed-chunk-87-1.png" width="672" />
</details>
<p><br></p>
<p>Try a square root transformation of <code>rate_unemployment</code></p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="edgap.html#cb156-1"></a>fit_ru_sqrt &lt;-<span class="st"> </span><span class="kw">lm</span>(average_act <span class="op">~</span><span class="st"> </span><span class="kw">sqrt</span>(rate_unemployment), <span class="dt">data =</span> edgap)</span></code></pre></div>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="edgap.html#cb157-1"></a><span class="kw">summary</span>(fit_ru_sqrt)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = average_act ~ sqrt(rate_unemployment), data = edgap)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.8203 -1.4328  0.0892  1.4497 12.1147 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              23.9672     0.0934  256.61   &lt;2e-16 ***
## sqrt(rate_unemployment) -12.4488     0.2983  -41.74   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.289 on 7879 degrees of freedom
##   (17 observations deleted due to missingness)
## Multiple R-squared:  0.1811, Adjusted R-squared:  0.181 
## F-statistic:  1742 on 1 and 7879 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The square root transformation provides a small improvement over the linear model.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="edgap.html#cb159-1"></a><span class="kw">ggplot</span>(edgap, <span class="kw">aes</span>(<span class="dt">x =</span> rate_unemployment, <span class="dt">y =</span> average_act)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb159-2"><a href="edgap.html#cb159-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb159-3"><a href="edgap.html#cb159-3"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>,<span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x) <span class="op">+</span></span>
<span id="cb159-4"><a href="edgap.html#cb159-4"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>,<span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span><span class="kw">sqrt</span>(x),<span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span></span>
<span id="cb159-5"><a href="edgap.html#cb159-5"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Unemployment rate&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;School ACT average (or equivalent if SAT score)&quot;</span>) <span class="op">+</span></span>
<span id="cb159-6"><a href="edgap.html#cb159-6"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 17 rows containing non-finite values (stat_smooth).

## Warning: Removed 17 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 17 rows containing missing values (geom_point).</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-90-1.png" width="672" /></p>
<p>The models are very similar for most of the data, but differ a lot for high unemployment rates. There are few data points with high unemployment rates, so the numerical measures of accuracy are very similar.</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="edgap.html#cb162-1"></a><span class="kw">ggplot</span>(fit_ru_sqrt,<span class="kw">aes</span>(<span class="dt">x=</span>.fitted, <span class="dt">y=</span>.resid)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb162-2"><a href="edgap.html#cb162-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb162-3"><a href="edgap.html#cb162-3"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;loess&quot;</span>, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x) <span class="op">+</span></span>
<span id="cb162-4"><a href="edgap.html#cb162-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Square root of unemployment rate&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Residuals&quot;</span>) <span class="op">+</span></span>
<span id="cb162-5"><a href="edgap.html#cb162-5"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-91-1.png" width="672" /></p>
</details>
<p><br></p>
</div>
<div id="percent-married" class="section level4">
<h4><span class="header-section-number">2.5.1.5</span> Percent married</h4>
<p><strong>Fit a model</strong></p>
<p>We want to fit the simple linear regression model</p>
<p><code>average_act</code> <span class="math inline">\(\approx \beta_0 + \beta_1\)</span> <code>percent_married</code></p>
<p><span class="math inline">\(\rightarrow\)</span> Use the function <code>lm</code> to fit a simple linear regression model.</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="edgap.html#cb163-1"></a>fit_pm &lt;-<span class="st"> </span><span class="kw">lm</span>(average_act <span class="op">~</span><span class="st"> </span>percent_married, <span class="dt">data =</span> edgap)</span></code></pre></div>
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Use the <code>summary</code> function to:</p>
<ol style="list-style-type: decimal">
<li>Interpret the coefficients in the model.</li>
<li>Assess the statistical significance of the coefficient on the predictor variable.</li>
</ol>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="edgap.html#cb164-1"></a><span class="kw">summary</span>(fit_pm)<span class="op">$</span>coefficients</span></code></pre></div>
<pre><code>##                  Estimate Std. Error   t value Pr(&gt;|t|)
## (Intercept)     16.626092 0.08750344 190.00502        0
## percent_married  5.653359 0.13162329  42.95106        0</code></pre>
The slope is highly statistically significant. So, there is a statistically significant relationship between percent married and the average ACT score in a school.
</details>
<p><br></p>
<p><span class="math inline">\(\rightarrow\)</span> Plot the regression line together with the scatter plot</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="edgap.html#cb166-1"></a><span class="kw">ggplot</span>(edgap, <span class="kw">aes</span>(<span class="dt">x =</span> percent_married, <span class="dt">y =</span> average_act)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb166-2"><a href="edgap.html#cb166-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb166-3"><a href="edgap.html#cb166-3"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>,<span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x) <span class="op">+</span></span>
<span id="cb166-4"><a href="edgap.html#cb166-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Percent married&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;School ACT average (or equivalent if SAT score)&quot;</span>) <span class="op">+</span></span>
<span id="cb166-5"><a href="edgap.html#cb166-5"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 27 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 27 rows containing missing values (geom_point).</code></pre>
<img src="bookdown-demo_files/figure-html/unnamed-chunk-94-1.png" width="672" />
</details>
<p><br></p>
<p><strong>Assess the accuracy of the fit</strong></p>
<p><span class="math inline">\(\rightarrow\)</span> Examine the <span class="math inline">\(R^2\)</span> and the residual standard error</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="edgap.html#cb169-1"></a><span class="kw">summary</span>(fit_pm)<span class="op">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.1899148</code></pre>
<p>The simple linear regression model using percent married as a predictor can explain 19% in the variance of the ACT score.</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="edgap.html#cb171-1"></a><span class="kw">summary</span>(fit_pm)<span class="op">$</span>sigma</span></code></pre></div>
<pre><code>## [1] 2.276227</code></pre>
<p>The residual standard error is 2.28 points. This means that the model is off by about 2.28 points, on average.</p>
Together, these results show that we can do some moderate prediction of the average ACT score in a school only by knowing the median income.
</details>
<p><br></p>
<p><strong>Residual plot</strong></p>
<p><span class="math inline">\(\rightarrow\)</span> Examine a residual plot to see if we can improve the model.</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="edgap.html#cb173-1"></a><span class="kw">ggplot</span>(fit_pm,<span class="kw">aes</span>(<span class="dt">x=</span>percent_married, <span class="dt">y=</span>.resid)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb173-2"><a href="edgap.html#cb173-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb173-3"><a href="edgap.html#cb173-3"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;loess&quot;</span>, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x) <span class="op">+</span></span>
<span id="cb173-4"><a href="edgap.html#cb173-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Percent married&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Residuals&quot;</span>) <span class="op">+</span></span>
<span id="cb173-5"><a href="edgap.html#cb173-5"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-97-1.png" width="672" /></p>
<p>The residual plot suggests a quadratic model may be useful.</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="edgap.html#cb174-1"></a>fit_pm_quad &lt;-<span class="st"> </span><span class="kw">lm</span>(average_act <span class="op">~</span><span class="st"> </span><span class="kw">poly</span>(percent_married, <span class="dv">2</span>, <span class="dt">raw =</span> T), <span class="dt">data =</span> edgap)</span></code></pre></div>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="edgap.html#cb175-1"></a><span class="kw">summary</span>(fit_pm_quad)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = average_act ~ poly(percent_married, 2, raw = T), 
##     data = edgap)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.0512 -1.4475  0.0431  1.4056 10.8912 
## 
## Coefficients:
##                                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                         17.0775     0.1669 102.315  &lt; 2e-16 ***
## poly(percent_married, 2, raw = T)1   3.7933     0.6005   6.317 2.81e-10 ***
## poly(percent_married, 2, raw = T)2   1.6537     0.5209   3.175   0.0015 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.275 on 7868 degrees of freedom
##   (27 observations deleted due to missingness)
## Multiple R-squared:  0.191,  Adjusted R-squared:  0.1907 
## F-statistic: 928.5 on 2 and 7868 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The quadratic term is statistically significant, even though the improvement in accuracy is not large.</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="edgap.html#cb177-1"></a><span class="kw">ggplot</span>(edgap, <span class="kw">aes</span>(<span class="dt">x =</span> percent_married, <span class="dt">y =</span> average_act)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb177-2"><a href="edgap.html#cb177-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb177-3"><a href="edgap.html#cb177-3"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>,<span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span>x) <span class="op">+</span></span>
<span id="cb177-4"><a href="edgap.html#cb177-4"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>,<span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span><span class="kw">poly</span>(x,<span class="dv">2</span>), <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>) <span class="op">+</span></span>
<span id="cb177-5"><a href="edgap.html#cb177-5"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Percent married&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;School ACT average (or equivalent if SAT score)&quot;</span>) <span class="op">+</span></span>
<span id="cb177-6"><a href="edgap.html#cb177-6"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 27 rows containing non-finite values (stat_smooth).

## Warning: Removed 27 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 27 rows containing missing values (geom_point).</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-100-1.png" width="672" /></p>
<p>The graph shows that the models are nearly identical.</p>
</details>
<p><br></p>
</div>
</div>
<div id="model-selection" class="section level3">
<h3><span class="header-section-number">2.5.2</span> Model selection</h3>
<p>Now that understand how each variable is individually related to the ACT score, we want to know how to best use all of the socioeconomic variables to predict the ACT score.</p>
<p>We do not have many input variables, so we can examine the full model.</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="edgap.html#cb180-1"></a>fit_full &lt;-<span class="st"> </span><span class="kw">lm</span>(average_act <span class="op">~</span><span class="st"> </span>percent_lunch <span class="op">+</span><span class="st"> </span>median_income <span class="op">+</span><span class="st"> </span>rate_unemployment <span class="op">+</span><span class="st"> </span>percent_college <span class="op">+</span><span class="st"> </span>percent_married, <span class="dt">data =</span> edgap)</span></code></pre></div>
<p>Examine the summary of the fit</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="edgap.html#cb181-1"></a><span class="kw">summary</span>(fit_full)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = average_act ~ percent_lunch + median_income + rate_unemployment + 
##     percent_college + percent_married, data = edgap)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.5200 -0.9542 -0.0908  0.8780 10.8438 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        2.272e+01  1.321e-01 172.003  &lt; 2e-16 ***
## percent_lunch     -7.590e+00  9.230e-02 -82.230  &lt; 2e-16 ***
## median_income     -3.392e-07  1.185e-06  -0.286    0.775    
## rate_unemployment -2.200e+00  3.870e-01  -5.685 1.35e-08 ***
## percent_college    1.669e+00  1.520e-01  10.986  &lt; 2e-16 ***
## percent_married   -6.412e-02  1.273e-01  -0.504    0.615    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.551 on 7845 degrees of freedom
##   (47 observations deleted due to missingness)
## Multiple R-squared:  0.6242, Adjusted R-squared:  0.6239 
## F-statistic:  2606 on 5 and 7845 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The coefficients for <code>median_income</code> and <code>percent_married</code> are not statistically significant. Additionally, the sign of the coefficients for <code>median_income</code> and <code>percent_married</code> do not make sense. These results support removing <code>median_income</code> and <code>percent_married</code> from the model.</p>
<div id="do-best-subset-selection" class="section level4">
<h4><span class="header-section-number">2.5.2.1</span> Do best subset selection</h4>
<p>Use the <code>regsubsets</code> function from the <code>leaps</code> package to perform best subset selection in order to choose the best model to predict <code>average_act</code> from the socioeconomic predictors.</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="edgap.html#cb183-1"></a><span class="co">#perform best subset selection</span></span>
<span id="cb183-2"><a href="edgap.html#cb183-2"></a>regfit_full &lt;-<span class="st"> </span><span class="kw">regsubsets</span>(average_act <span class="op">~</span><span class="st"> </span>percent_lunch <span class="op">+</span><span class="st"> </span>median_income <span class="op">+</span><span class="st"> </span>rate_unemployment <span class="op">+</span><span class="st"> </span>percent_college <span class="op">+</span><span class="st"> </span>percent_married, <span class="dt">data =</span> edgap)</span></code></pre></div>
<p>Get the summary of the best subset selection analysis</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="edgap.html#cb184-1"></a>reg_summary &lt;-<span class="st"> </span><span class="kw">summary</span>(regfit_full)</span></code></pre></div>
<p>What is the best model obtained according to Cp, BIC, and adjusted <span class="math inline">\(R^2\)</span>? Make a plot of Cp, BIC, and adjusted <span class="math inline">\(R^2\)</span> vs. the number of variables in the model.</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="edgap.html#cb185-1"></a><span class="co">#Set up a three panel plot</span></span>
<span id="cb185-2"><a href="edgap.html#cb185-2"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb185-3"><a href="edgap.html#cb185-3"></a></span>
<span id="cb185-4"><a href="edgap.html#cb185-4"></a><span class="co">#Plot Cp</span></span>
<span id="cb185-5"><a href="edgap.html#cb185-5"></a><span class="kw">plot</span>(reg_summary<span class="op">$</span>cp,<span class="dt">type =</span> <span class="st">&quot;b&quot;</span>,<span class="dt">xlab =</span> <span class="st">&quot;Number of variables&quot;</span>,<span class="dt">ylab =</span> <span class="st">&quot;Cp&quot;</span>)</span>
<span id="cb185-6"><a href="edgap.html#cb185-6"></a><span class="co">#Identify the minimum Cp</span></span>
<span id="cb185-7"><a href="edgap.html#cb185-7"></a>ind_cp =<span class="st"> </span><span class="kw">which.min</span>(reg_summary<span class="op">$</span>cp)</span>
<span id="cb185-8"><a href="edgap.html#cb185-8"></a><span class="kw">points</span>(ind_cp, reg_summary<span class="op">$</span>cp[ind_cp],<span class="dt">col =</span> <span class="st">&quot;red&quot;</span>,<span class="dt">pch =</span> <span class="dv">20</span>)</span>
<span id="cb185-9"><a href="edgap.html#cb185-9"></a></span>
<span id="cb185-10"><a href="edgap.html#cb185-10"></a><span class="co">#Plot BIC</span></span>
<span id="cb185-11"><a href="edgap.html#cb185-11"></a><span class="kw">plot</span>(reg_summary<span class="op">$</span>bic,<span class="dt">type =</span> <span class="st">&quot;b&quot;</span>,<span class="dt">xlab =</span> <span class="st">&quot;Number of variables&quot;</span>,<span class="dt">ylab =</span> <span class="st">&quot;BIC&quot;</span>)</span>
<span id="cb185-12"><a href="edgap.html#cb185-12"></a><span class="co">#Identify the minimum BIC</span></span>
<span id="cb185-13"><a href="edgap.html#cb185-13"></a>ind_bic =<span class="st"> </span><span class="kw">which.min</span>(reg_summary<span class="op">$</span>bic)</span>
<span id="cb185-14"><a href="edgap.html#cb185-14"></a><span class="kw">points</span>(ind_bic, reg_summary<span class="op">$</span>bic[ind_bic],<span class="dt">col =</span> <span class="st">&quot;red&quot;</span>,<span class="dt">pch =</span> <span class="dv">20</span>)</span>
<span id="cb185-15"><a href="edgap.html#cb185-15"></a></span>
<span id="cb185-16"><a href="edgap.html#cb185-16"></a><span class="co">#Plot adjusted R^2</span></span>
<span id="cb185-17"><a href="edgap.html#cb185-17"></a><span class="kw">plot</span>(reg_summary<span class="op">$</span>adjr2,<span class="dt">type =</span> <span class="st">&quot;b&quot;</span>,<span class="dt">xlab =</span> <span class="st">&quot;Number of variables&quot;</span>,<span class="dt">ylab =</span> <span class="kw">TeX</span>(<span class="st">&#39;Adjusted $R^2$&#39;</span>),<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb185-18"><a href="edgap.html#cb185-18"></a></span>
<span id="cb185-19"><a href="edgap.html#cb185-19"></a><span class="co">#Identify the maximum adjusted R^2</span></span>
<span id="cb185-20"><a href="edgap.html#cb185-20"></a>ind_adjr2 =<span class="st"> </span><span class="kw">which.max</span>(reg_summary<span class="op">$</span>adjr2)</span>
<span id="cb185-21"><a href="edgap.html#cb185-21"></a><span class="kw">points</span>(ind_adjr2, reg_summary<span class="op">$</span>adjr2[ind_adjr2],<span class="dt">col =</span> <span class="st">&quot;red&quot;</span>,<span class="dt">pch =</span> <span class="dv">20</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-105-1.png" width="672" /></p>
<p>The three measures agree that the best model has three variables.</p>
<p>Show the best model for each possible number of variables. Focus on the three variable model.</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="edgap.html#cb186-1"></a>reg_summary<span class="op">$</span>outmat</span></code></pre></div>
<pre><code>##          percent_lunch median_income rate_unemployment percent_college
## 1  ( 1 ) &quot;*&quot;           &quot; &quot;           &quot; &quot;               &quot; &quot;            
## 2  ( 1 ) &quot;*&quot;           &quot; &quot;           &quot; &quot;               &quot;*&quot;            
## 3  ( 1 ) &quot;*&quot;           &quot; &quot;           &quot;*&quot;               &quot;*&quot;            
## 4  ( 1 ) &quot;*&quot;           &quot; &quot;           &quot;*&quot;               &quot;*&quot;            
## 5  ( 1 ) &quot;*&quot;           &quot;*&quot;           &quot;*&quot;               &quot;*&quot;            
##          percent_married
## 1  ( 1 ) &quot; &quot;            
## 2  ( 1 ) &quot; &quot;            
## 3  ( 1 ) &quot; &quot;            
## 4  ( 1 ) &quot;*&quot;            
## 5  ( 1 ) &quot;*&quot;</code></pre>
<p>The best model uses the predictors <code>percent_lunch</code>, <code>rate_unemployment</code> and <code>percent_college</code>.</p>
<p>Fit the best model and examine the results</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="edgap.html#cb188-1"></a>fit_best &lt;-<span class="st"> </span><span class="kw">lm</span>(average_act <span class="op">~</span><span class="st"> </span>percent_lunch <span class="op">+</span><span class="st"> </span>rate_unemployment <span class="op">+</span><span class="st"> </span>percent_college, <span class="dt">data =</span> edgap)</span></code></pre></div>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="edgap.html#cb189-1"></a><span class="kw">summary</span>(fit_best)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = average_act ~ percent_lunch + rate_unemployment + 
##     percent_college, data = edgap)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.4792 -0.9550 -0.0916  0.8758 10.8014 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       22.64338    0.09800 231.057  &lt; 2e-16 ***
## percent_lunch     -7.58151    0.08801 -86.144  &lt; 2e-16 ***
## rate_unemployment -1.91829    0.35214  -5.447 5.26e-08 ***
## percent_college    1.65519    0.12187  13.581  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.552 on 7857 degrees of freedom
##   (37 observations deleted due to missingness)
## Multiple R-squared:  0.6235, Adjusted R-squared:  0.6234 
## F-statistic:  4338 on 3 and 7857 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="relative-importance-of-predictors" class="section level4">
<h4><span class="header-section-number">2.5.2.2</span> Relative importance of predictors</h4>
<p>To compare the magnitude of the coefficients, we should first normalize the predictors. Each of the predictors <code>percent_lunch</code>, <code>rate_unemployment</code> and <code>percent_college</code> is limited to the interval (0,1), but they occupy different parts of the interval. We can normalize each variable through a z-score transformation:</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="edgap.html#cb191-1"></a>scale_z &lt;-<span class="st"> </span><span class="cf">function</span>(x, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>) (x <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(x, <span class="dt">na.rm =</span> na.rm)) <span class="op">/</span><span class="st"> </span><span class="kw">sd</span>(x, na.rm)</span>
<span id="cb191-2"><a href="edgap.html#cb191-2"></a></span>
<span id="cb191-3"><a href="edgap.html#cb191-3"></a>edgap_z &lt;-<span class="st"> </span>edgap <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb191-4"><a href="edgap.html#cb191-4"></a><span class="st">  </span><span class="kw">mutate_at</span>(<span class="kw">c</span>(<span class="st">&quot;percent_lunch&quot;</span>,<span class="st">&quot;rate_unemployment&quot;</span>,<span class="st">&quot;percent_college&quot;</span>),scale_z) </span></code></pre></div>
<p><span class="math inline">\(\rightarrow\)</span> Fit the model using the transformed variables and examine the coefficients</p>
<details>
<p><summary><strong>Show Answer</strong></summary></p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="edgap.html#cb192-1"></a>fit_z &lt;-<span class="st"> </span><span class="kw">lm</span>(average_act <span class="op">~</span><span class="st"> </span>percent_lunch <span class="op">+</span><span class="st"> </span>rate_unemployment <span class="op">+</span><span class="st"> </span>percent_college, <span class="dt">data =</span> edgap_z)</span>
<span id="cb192-2"><a href="edgap.html#cb192-2"></a></span>
<span id="cb192-3"><a href="edgap.html#cb192-3"></a><span class="kw">summary</span>(fit_z)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = average_act ~ percent_lunch + rate_unemployment + 
##     percent_college, data = edgap_z)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.4792 -0.9550 -0.0916  0.8758 10.8014 
## 
## Coefficients:
##                   Estimate Std. Error  t value Pr(&gt;|t|)    
## (Intercept)       20.21841    0.01751 1154.965  &lt; 2e-16 ***
## percent_lunch     -1.80206    0.02092  -86.144  &lt; 2e-16 ***
## rate_unemployment -0.11166    0.02050   -5.447 5.26e-08 ***
## percent_college    0.27459    0.02022   13.581  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.552 on 7857 degrees of freedom
##   (37 observations deleted due to missingness)
## Multiple R-squared:  0.6235, Adjusted R-squared:  0.6234 
## F-statistic:  4338 on 3 and 7857 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The coefficient on <code>percent_lunch</code> is an order of magnitude larger than the other coefficients. This supports the conclusion that <code>percent_lunch</code> is the most important predictor.</p>
Additionally, the performance of the single predictor model using <code>percent_lunch</code> is very close to the performance of the best model.
</details>
</div>
</div>
</div>
<div id="additional-step" class="section level2">
<h2><span class="header-section-number">2.6</span> Additional step</h2>
<p>In addition to completing the above analyses, you should ask and answer one question about the data set.</p>
</div>
<div id="conclusion" class="section level2">
<h2><span class="header-section-number">2.7</span> Conclusion</h2>
<p>After completing your analyses, you will make your conclusions and communicate your results. Consult Canvas for further directions.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/01-EdGap-project-bookdown.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
